// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
		{Name: "action", Type: field.TypeString},
		{Name: "resource_type", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeString, Nullable: true},
		{Name: "detail", Type: field.TypeJSON, Nullable: true},
		{Name: "ip", Type: field.TypeString, Nullable: true},
		{Name: "prev_hash", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_user_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[1]},
			},
			{
				Name:    "auditlog_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[3], AuditLogsColumns[4]},
			},
			{
				Name:    "auditlog_action",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[2]},
			},
			{
				Name:    "auditlog_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[8]},
			},
		},
	}
	// ClustersColumns holds the columns for the "clusters" table.
	ClustersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "api_server", Type: field.TypeString},
		{Name: "kubeconfig_encrypted", Type: field.TypeBytes, Nullable: true},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "org_id", Type: field.TypeString, Nullable: true},
	}
	// ClustersTable holds the schema information for the "clusters" table.
	ClustersTable = &schema.Table{
		Name:       "clusters",
		Columns:    ClustersColumns,
		PrimaryKey: []*schema.Column{ClustersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "clusters_organizations_clusters",
				Columns:    []*schema.Column{ClustersColumns[8]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "cluster_org_id",
				Unique:  false,
				Columns: []*schema.Column{ClustersColumns[8]},
			},
			{
				Name:    "cluster_name",
				Unique:  false,
				Columns: []*schema.Column{ClustersColumns[1]},
			},
			{
				Name:    "cluster_status",
				Unique:  false,
				Columns: []*schema.Column{ClustersColumns[5]},
			},
		},
	}
	// EnvironmentsColumns holds the columns for the "environments" table.
	EnvironmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeEnum, Enums: []string{"dev", "test", "pre", "prod"}},
		{Name: "namespace_pattern", Type: field.TypeString, Nullable: true},
		{Name: "approval_required", Type: field.TypeBool, Default: false},
		{Name: "approver_role", Type: field.TypeString, Nullable: true},
		{Name: "config_overrides", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "cluster_id", Type: field.TypeString, Nullable: true},
		{Name: "org_id", Type: field.TypeString, Nullable: true},
	}
	// EnvironmentsTable holds the schema information for the "environments" table.
	EnvironmentsTable = &schema.Table{
		Name:       "environments",
		Columns:    EnvironmentsColumns,
		PrimaryKey: []*schema.Column{EnvironmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "environments_clusters_environments",
				Columns:    []*schema.Column{EnvironmentsColumns[8]},
				RefColumns: []*schema.Column{ClustersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "environments_organizations_environments",
				Columns:    []*schema.Column{EnvironmentsColumns[9]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "environment_org_id",
				Unique:  false,
				Columns: []*schema.Column{EnvironmentsColumns[9]},
			},
			{
				Name:    "environment_cluster_id",
				Unique:  false,
				Columns: []*schema.Column{EnvironmentsColumns[8]},
			},
			{
				Name:    "environment_name",
				Unique:  false,
				Columns: []*schema.Column{EnvironmentsColumns[1]},
			},
		},
	}
	// OrganizationsColumns holds the columns for the "organizations" table.
	OrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OrganizationsTable holds the schema information for the "organizations" table.
	OrganizationsTable = &schema.Table{
		Name:       "organizations",
		Columns:    OrganizationsColumns,
		PrimaryKey: []*schema.Column{OrganizationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "organization_slug",
				Unique:  false,
				Columns: []*schema.Column{OrganizationsColumns[2]},
			},
			{
				Name:    "organization_status",
				Unique:  false,
				Columns: []*schema.Column{OrganizationsColumns[4]},
			},
		},
	}
	// RegistriesColumns holds the columns for the "registries" table.
	RegistriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"harbor"}, Default: "harbor"},
		{Name: "url", Type: field.TypeString},
		{Name: "credentials_ref", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "org_id", Type: field.TypeString, Nullable: true},
	}
	// RegistriesTable holds the schema information for the "registries" table.
	RegistriesTable = &schema.Table{
		Name:       "registries",
		Columns:    RegistriesColumns,
		PrimaryKey: []*schema.Column{RegistriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "registries_organizations_registries",
				Columns:    []*schema.Column{RegistriesColumns[7]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "registry_org_id",
				Unique:  false,
				Columns: []*schema.Column{RegistriesColumns[7]},
			},
			{
				Name:    "registry_name",
				Unique:  false,
				Columns: []*schema.Column{RegistriesColumns[1]},
			},
			{
				Name:    "registry_type",
				Unique:  false,
				Columns: []*schema.Column{RegistriesColumns[2]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeEnum, Enums: []string{"admin", "operator", "developer", "viewer", "auditor"}},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// ServicesColumns holds the columns for the "services" table.
	ServicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "team", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
		{Name: "harbor_project", Type: field.TypeString, Nullable: true},
		{Name: "git_repo", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "org_id", Type: field.TypeString, Nullable: true},
	}
	// ServicesTable holds the schema information for the "services" table.
	ServicesTable = &schema.Table{
		Name:       "services",
		Columns:    ServicesColumns,
		PrimaryKey: []*schema.Column{ServicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "services_organizations_services",
				Columns:    []*schema.Column{ServicesColumns[10]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "service_org_id_name",
				Unique:  true,
				Columns: []*schema.Column{ServicesColumns[10], ServicesColumns[1]},
			},
			{
				Name:    "service_org_id",
				Unique:  false,
				Columns: []*schema.Column{ServicesColumns[10]},
			},
			{
				Name:    "service_name",
				Unique:  false,
				Columns: []*schema.Column{ServicesColumns[1]},
			},
			{
				Name:    "service_team",
				Unique:  false,
				Columns: []*schema.Column{ServicesColumns[2]},
			},
			{
				Name:    "service_status",
				Unique:  false,
				Columns: []*schema.Column{ServicesColumns[5]},
			},
		},
	}
	// SystemSettingsColumns holds the columns for the "system_settings" table.
	SystemSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "org_id", Type: field.TypeString, Nullable: true},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString, Default: ""},
		{Name: "encrypted", Type: field.TypeBool, Default: false},
		{Name: "category", Type: field.TypeEnum, Enums: []string{"argocd", "harbor", "git", "notification", "general"}, Default: "general"},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SystemSettingsTable holds the schema information for the "system_settings" table.
	SystemSettingsTable = &schema.Table{
		Name:       "system_settings",
		Columns:    SystemSettingsColumns,
		PrimaryKey: []*schema.Column{SystemSettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "systemsetting_org_id",
				Unique:  false,
				Columns: []*schema.Column{SystemSettingsColumns[1]},
			},
			{
				Name:    "systemsetting_category",
				Unique:  false,
				Columns: []*schema.Column{SystemSettingsColumns[5]},
			},
			{
				Name:    "systemsetting_key",
				Unique:  false,
				Columns: []*schema.Column{SystemSettingsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "oidc_subject", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "org_id", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_organizations_users",
				Columns:    []*schema.Column{UsersColumns[7]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
			},
			{
				Name:    "user_oidc_subject",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
			{
				Name:    "user_org_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[7]},
			},
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditLogsTable,
		ClustersTable,
		EnvironmentsTable,
		OrganizationsTable,
		RegistriesTable,
		RolesTable,
		ServicesTable,
		SystemSettingsTable,
		UsersTable,
	}
)

func init() {
	ClustersTable.ForeignKeys[0].RefTable = OrganizationsTable
	EnvironmentsTable.ForeignKeys[0].RefTable = ClustersTable
	EnvironmentsTable.ForeignKeys[1].RefTable = OrganizationsTable
	RegistriesTable.ForeignKeys[0].RefTable = OrganizationsTable
	ServicesTable.ForeignKeys[0].RefTable = OrganizationsTable
	UsersTable.ForeignKeys[0].RefTable = OrganizationsTable
}
