// Code generated by ent, DO NOT EDIT.

package environment

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the environment type in the database.
	Label = "environment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrgID holds the string denoting the org_id field in the database.
	FieldOrgID = "org_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldClusterID holds the string denoting the cluster_id field in the database.
	FieldClusterID = "cluster_id"
	// FieldNamespacePattern holds the string denoting the namespace_pattern field in the database.
	FieldNamespacePattern = "namespace_pattern"
	// FieldApprovalRequired holds the string denoting the approval_required field in the database.
	FieldApprovalRequired = "approval_required"
	// FieldApproverRole holds the string denoting the approver_role field in the database.
	FieldApproverRole = "approver_role"
	// FieldConfigOverrides holds the string denoting the config_overrides field in the database.
	FieldConfigOverrides = "config_overrides"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCluster holds the string denoting the cluster edge name in mutations.
	EdgeCluster = "cluster"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// Table holds the table name of the environment in the database.
	Table = "environments"
	// ClusterTable is the table that holds the cluster relation/edge.
	ClusterTable = "environments"
	// ClusterInverseTable is the table name for the Cluster entity.
	// It exists in this package in order to avoid circular dependency with the "cluster" package.
	ClusterInverseTable = "clusters"
	// ClusterColumn is the table column denoting the cluster relation/edge.
	ClusterColumn = "cluster_id"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "environments"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "org_id"
)

// Columns holds all SQL columns for environment fields.
var Columns = []string{
	FieldID,
	FieldOrgID,
	FieldName,
	FieldClusterID,
	FieldNamespacePattern,
	FieldApprovalRequired,
	FieldApproverRole,
	FieldConfigOverrides,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultApprovalRequired holds the default value on creation for the "approval_required" field.
	DefaultApprovalRequired bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Name defines the type for the "name" enum field.
type Name string

// Name values.
const (
	NameDev  Name = "dev"
	NameTest Name = "test"
	NamePre  Name = "pre"
	NameProd Name = "prod"
)

func (n Name) String() string {
	return string(n)
}

// NameValidator is a validator for the "name" field enum values. It is called by the builders before save.
func NameValidator(n Name) error {
	switch n {
	case NameDev, NameTest, NamePre, NameProd:
		return nil
	default:
		return fmt.Errorf("environment: invalid enum value for name field: %q", n)
	}
}

// OrderOption defines the ordering options for the Environment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrgID orders the results by the org_id field.
func ByOrgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByClusterID orders the results by the cluster_id field.
func ByClusterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClusterID, opts...).ToFunc()
}

// ByNamespacePattern orders the results by the namespace_pattern field.
func ByNamespacePattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespacePattern, opts...).ToFunc()
}

// ByApprovalRequired orders the results by the approval_required field.
func ByApprovalRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovalRequired, opts...).ToFunc()
}

// ByApproverRole orders the results by the approver_role field.
func ByApproverRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApproverRole, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByClusterField orders the results by cluster field.
func ByClusterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClusterStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}
func newClusterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClusterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClusterTable, ClusterColumn),
	)
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
	)
}
