// Code generated by ent, DO NOT EDIT.

package registry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/whg517/fleet/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Registry {
	return predicate.Registry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Registry {
	return predicate.Registry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Registry {
	return predicate.Registry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Registry {
	return predicate.Registry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Registry {
	return predicate.Registry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Registry {
	return predicate.Registry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Registry {
	return predicate.Registry(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Registry {
	return predicate.Registry(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Registry {
	return predicate.Registry(sql.FieldContainsFold(FieldID, id))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldOrgID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldName, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldURL, v))
}

// CredentialsRef applies equality check predicate on the "credentials_ref" field. It's identical to CredentialsRefEQ.
func CredentialsRef(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldCredentialsRef, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v string) predicate.Registry {
	return predicate.Registry(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...string) predicate.Registry {
	return predicate.Registry(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...string) predicate.Registry {
	return predicate.Registry(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v string) predicate.Registry {
	return predicate.Registry(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v string) predicate.Registry {
	return predicate.Registry(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v string) predicate.Registry {
	return predicate.Registry(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v string) predicate.Registry {
	return predicate.Registry(sql.FieldLTE(FieldOrgID, v))
}

// OrgIDContains applies the Contains predicate on the "org_id" field.
func OrgIDContains(v string) predicate.Registry {
	return predicate.Registry(sql.FieldContains(FieldOrgID, v))
}

// OrgIDHasPrefix applies the HasPrefix predicate on the "org_id" field.
func OrgIDHasPrefix(v string) predicate.Registry {
	return predicate.Registry(sql.FieldHasPrefix(FieldOrgID, v))
}

// OrgIDHasSuffix applies the HasSuffix predicate on the "org_id" field.
func OrgIDHasSuffix(v string) predicate.Registry {
	return predicate.Registry(sql.FieldHasSuffix(FieldOrgID, v))
}

// OrgIDIsNil applies the IsNil predicate on the "org_id" field.
func OrgIDIsNil() predicate.Registry {
	return predicate.Registry(sql.FieldIsNull(FieldOrgID))
}

// OrgIDNotNil applies the NotNil predicate on the "org_id" field.
func OrgIDNotNil() predicate.Registry {
	return predicate.Registry(sql.FieldNotNull(FieldOrgID))
}

// OrgIDEqualFold applies the EqualFold predicate on the "org_id" field.
func OrgIDEqualFold(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEqualFold(FieldOrgID, v))
}

// OrgIDContainsFold applies the ContainsFold predicate on the "org_id" field.
func OrgIDContainsFold(v string) predicate.Registry {
	return predicate.Registry(sql.FieldContainsFold(FieldOrgID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Registry {
	return predicate.Registry(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Registry {
	return predicate.Registry(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Registry {
	return predicate.Registry(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Registry {
	return predicate.Registry(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Registry {
	return predicate.Registry(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Registry {
	return predicate.Registry(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Registry {
	return predicate.Registry(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Registry {
	return predicate.Registry(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Registry {
	return predicate.Registry(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Registry {
	return predicate.Registry(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Registry {
	return predicate.Registry(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Registry {
	return predicate.Registry(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Registry {
	return predicate.Registry(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Registry {
	return predicate.Registry(sql.FieldNotIn(FieldType, vs...))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Registry {
	return predicate.Registry(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Registry {
	return predicate.Registry(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Registry {
	return predicate.Registry(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Registry {
	return predicate.Registry(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Registry {
	return predicate.Registry(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Registry {
	return predicate.Registry(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Registry {
	return predicate.Registry(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Registry {
	return predicate.Registry(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Registry {
	return predicate.Registry(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Registry {
	return predicate.Registry(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Registry {
	return predicate.Registry(sql.FieldContainsFold(FieldURL, v))
}

// CredentialsRefEQ applies the EQ predicate on the "credentials_ref" field.
func CredentialsRefEQ(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldCredentialsRef, v))
}

// CredentialsRefNEQ applies the NEQ predicate on the "credentials_ref" field.
func CredentialsRefNEQ(v string) predicate.Registry {
	return predicate.Registry(sql.FieldNEQ(FieldCredentialsRef, v))
}

// CredentialsRefIn applies the In predicate on the "credentials_ref" field.
func CredentialsRefIn(vs ...string) predicate.Registry {
	return predicate.Registry(sql.FieldIn(FieldCredentialsRef, vs...))
}

// CredentialsRefNotIn applies the NotIn predicate on the "credentials_ref" field.
func CredentialsRefNotIn(vs ...string) predicate.Registry {
	return predicate.Registry(sql.FieldNotIn(FieldCredentialsRef, vs...))
}

// CredentialsRefGT applies the GT predicate on the "credentials_ref" field.
func CredentialsRefGT(v string) predicate.Registry {
	return predicate.Registry(sql.FieldGT(FieldCredentialsRef, v))
}

// CredentialsRefGTE applies the GTE predicate on the "credentials_ref" field.
func CredentialsRefGTE(v string) predicate.Registry {
	return predicate.Registry(sql.FieldGTE(FieldCredentialsRef, v))
}

// CredentialsRefLT applies the LT predicate on the "credentials_ref" field.
func CredentialsRefLT(v string) predicate.Registry {
	return predicate.Registry(sql.FieldLT(FieldCredentialsRef, v))
}

// CredentialsRefLTE applies the LTE predicate on the "credentials_ref" field.
func CredentialsRefLTE(v string) predicate.Registry {
	return predicate.Registry(sql.FieldLTE(FieldCredentialsRef, v))
}

// CredentialsRefContains applies the Contains predicate on the "credentials_ref" field.
func CredentialsRefContains(v string) predicate.Registry {
	return predicate.Registry(sql.FieldContains(FieldCredentialsRef, v))
}

// CredentialsRefHasPrefix applies the HasPrefix predicate on the "credentials_ref" field.
func CredentialsRefHasPrefix(v string) predicate.Registry {
	return predicate.Registry(sql.FieldHasPrefix(FieldCredentialsRef, v))
}

// CredentialsRefHasSuffix applies the HasSuffix predicate on the "credentials_ref" field.
func CredentialsRefHasSuffix(v string) predicate.Registry {
	return predicate.Registry(sql.FieldHasSuffix(FieldCredentialsRef, v))
}

// CredentialsRefIsNil applies the IsNil predicate on the "credentials_ref" field.
func CredentialsRefIsNil() predicate.Registry {
	return predicate.Registry(sql.FieldIsNull(FieldCredentialsRef))
}

// CredentialsRefNotNil applies the NotNil predicate on the "credentials_ref" field.
func CredentialsRefNotNil() predicate.Registry {
	return predicate.Registry(sql.FieldNotNull(FieldCredentialsRef))
}

// CredentialsRefEqualFold applies the EqualFold predicate on the "credentials_ref" field.
func CredentialsRefEqualFold(v string) predicate.Registry {
	return predicate.Registry(sql.FieldEqualFold(FieldCredentialsRef, v))
}

// CredentialsRefContainsFold applies the ContainsFold predicate on the "credentials_ref" field.
func CredentialsRefContainsFold(v string) predicate.Registry {
	return predicate.Registry(sql.FieldContainsFold(FieldCredentialsRef, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Registry {
	return predicate.Registry(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.Registry {
	return predicate.Registry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.Registry {
	return predicate.Registry(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Registry) predicate.Registry {
	return predicate.Registry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Registry) predicate.Registry {
	return predicate.Registry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Registry) predicate.Registry {
	return predicate.Registry(sql.NotPredicates(p))
}
