// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/approval"
	"github.com/whg517/fleet/internal/store/ent/deployment"
	"github.com/whg517/fleet/internal/store/ent/environment"
	"github.com/whg517/fleet/internal/store/ent/organization"
	"github.com/whg517/fleet/internal/store/ent/predicate"
	"github.com/whg517/fleet/internal/store/ent/service"
)

// ApprovalQuery is the builder for querying Approval entities.
type ApprovalQuery struct {
	config
	ctx              *QueryContext
	order            []approval.OrderOption
	inters           []Interceptor
	predicates       []predicate.Approval
	withDeployment   *DeploymentQuery
	withService      *ServiceQuery
	withEnvironment  *EnvironmentQuery
	withOrganization *OrganizationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApprovalQuery builder.
func (_q *ApprovalQuery) Where(ps ...predicate.Approval) *ApprovalQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ApprovalQuery) Limit(limit int) *ApprovalQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ApprovalQuery) Offset(offset int) *ApprovalQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ApprovalQuery) Unique(unique bool) *ApprovalQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ApprovalQuery) Order(o ...approval.OrderOption) *ApprovalQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDeployment chains the current query on the "deployment" edge.
func (_q *ApprovalQuery) QueryDeployment() *DeploymentQuery {
	query := (&DeploymentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(approval.Table, approval.FieldID, selector),
			sqlgraph.To(deployment.Table, deployment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, approval.DeploymentTable, approval.DeploymentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryService chains the current query on the "service" edge.
func (_q *ApprovalQuery) QueryService() *ServiceQuery {
	query := (&ServiceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(approval.Table, approval.FieldID, selector),
			sqlgraph.To(service.Table, service.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, approval.ServiceTable, approval.ServiceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEnvironment chains the current query on the "environment" edge.
func (_q *ApprovalQuery) QueryEnvironment() *EnvironmentQuery {
	query := (&EnvironmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(approval.Table, approval.FieldID, selector),
			sqlgraph.To(environment.Table, environment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, approval.EnvironmentTable, approval.EnvironmentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrganization chains the current query on the "organization" edge.
func (_q *ApprovalQuery) QueryOrganization() *OrganizationQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(approval.Table, approval.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, approval.OrganizationTable, approval.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Approval entity from the query.
// Returns a *NotFoundError when no Approval was found.
func (_q *ApprovalQuery) First(ctx context.Context) (*Approval, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{approval.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ApprovalQuery) FirstX(ctx context.Context) *Approval {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Approval ID from the query.
// Returns a *NotFoundError when no Approval ID was found.
func (_q *ApprovalQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{approval.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ApprovalQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Approval entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Approval entity is found.
// Returns a *NotFoundError when no Approval entities are found.
func (_q *ApprovalQuery) Only(ctx context.Context) (*Approval, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{approval.Label}
	default:
		return nil, &NotSingularError{approval.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ApprovalQuery) OnlyX(ctx context.Context) *Approval {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Approval ID in the query.
// Returns a *NotSingularError when more than one Approval ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ApprovalQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{approval.Label}
	default:
		err = &NotSingularError{approval.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ApprovalQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Approvals.
func (_q *ApprovalQuery) All(ctx context.Context) ([]*Approval, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Approval, *ApprovalQuery]()
	return withInterceptors[[]*Approval](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ApprovalQuery) AllX(ctx context.Context) []*Approval {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Approval IDs.
func (_q *ApprovalQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(approval.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ApprovalQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ApprovalQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ApprovalQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ApprovalQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ApprovalQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ApprovalQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApprovalQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ApprovalQuery) Clone() *ApprovalQuery {
	if _q == nil {
		return nil
	}
	return &ApprovalQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]approval.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Approval{}, _q.predicates...),
		withDeployment:   _q.withDeployment.Clone(),
		withService:      _q.withService.Clone(),
		withEnvironment:  _q.withEnvironment.Clone(),
		withOrganization: _q.withOrganization.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDeployment tells the query-builder to eager-load the nodes that are connected to
// the "deployment" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ApprovalQuery) WithDeployment(opts ...func(*DeploymentQuery)) *ApprovalQuery {
	query := (&DeploymentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDeployment = query
	return _q
}

// WithService tells the query-builder to eager-load the nodes that are connected to
// the "service" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ApprovalQuery) WithService(opts ...func(*ServiceQuery)) *ApprovalQuery {
	query := (&ServiceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withService = query
	return _q
}

// WithEnvironment tells the query-builder to eager-load the nodes that are connected to
// the "environment" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ApprovalQuery) WithEnvironment(opts ...func(*EnvironmentQuery)) *ApprovalQuery {
	query := (&EnvironmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEnvironment = query
	return _q
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ApprovalQuery) WithOrganization(opts ...func(*OrganizationQuery)) *ApprovalQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrganization = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrgID string `json:"org_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Approval.Query().
//		GroupBy(approval.FieldOrgID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ApprovalQuery) GroupBy(field string, fields ...string) *ApprovalGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ApprovalGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = approval.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrgID string `json:"org_id,omitempty"`
//	}
//
//	client.Approval.Query().
//		Select(approval.FieldOrgID).
//		Scan(ctx, &v)
func (_q *ApprovalQuery) Select(fields ...string) *ApprovalSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ApprovalSelect{ApprovalQuery: _q}
	sbuild.label = approval.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ApprovalSelect configured with the given aggregations.
func (_q *ApprovalQuery) Aggregate(fns ...AggregateFunc) *ApprovalSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ApprovalQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !approval.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ApprovalQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Approval, error) {
	var (
		nodes       = []*Approval{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withDeployment != nil,
			_q.withService != nil,
			_q.withEnvironment != nil,
			_q.withOrganization != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Approval).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Approval{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDeployment; query != nil {
		if err := _q.loadDeployment(ctx, query, nodes, nil,
			func(n *Approval, e *Deployment) { n.Edges.Deployment = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withService; query != nil {
		if err := _q.loadService(ctx, query, nodes, nil,
			func(n *Approval, e *Service) { n.Edges.Service = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEnvironment; query != nil {
		if err := _q.loadEnvironment(ctx, query, nodes, nil,
			func(n *Approval, e *Environment) { n.Edges.Environment = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOrganization; query != nil {
		if err := _q.loadOrganization(ctx, query, nodes, nil,
			func(n *Approval, e *Organization) { n.Edges.Organization = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ApprovalQuery) loadDeployment(ctx context.Context, query *DeploymentQuery, nodes []*Approval, init func(*Approval), assign func(*Approval, *Deployment)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Approval)
	for i := range nodes {
		fk := nodes[i].DeploymentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(deployment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "deployment_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ApprovalQuery) loadService(ctx context.Context, query *ServiceQuery, nodes []*Approval, init func(*Approval), assign func(*Approval, *Service)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Approval)
	for i := range nodes {
		fk := nodes[i].ServiceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(service.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "service_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ApprovalQuery) loadEnvironment(ctx context.Context, query *EnvironmentQuery, nodes []*Approval, init func(*Approval), assign func(*Approval, *Environment)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Approval)
	for i := range nodes {
		fk := nodes[i].EnvironmentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(environment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "environment_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ApprovalQuery) loadOrganization(ctx context.Context, query *OrganizationQuery, nodes []*Approval, init func(*Approval), assign func(*Approval, *Organization)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Approval)
	for i := range nodes {
		fk := nodes[i].OrgID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(organization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "org_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ApprovalQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ApprovalQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(approval.Table, approval.Columns, sqlgraph.NewFieldSpec(approval.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, approval.FieldID)
		for i := range fields {
			if fields[i] != approval.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withDeployment != nil {
			_spec.Node.AddColumnOnce(approval.FieldDeploymentID)
		}
		if _q.withService != nil {
			_spec.Node.AddColumnOnce(approval.FieldServiceID)
		}
		if _q.withEnvironment != nil {
			_spec.Node.AddColumnOnce(approval.FieldEnvironmentID)
		}
		if _q.withOrganization != nil {
			_spec.Node.AddColumnOnce(approval.FieldOrgID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ApprovalQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(approval.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = approval.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ApprovalGroupBy is the group-by builder for Approval entities.
type ApprovalGroupBy struct {
	selector
	build *ApprovalQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ApprovalGroupBy) Aggregate(fns ...AggregateFunc) *ApprovalGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ApprovalGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApprovalQuery, *ApprovalGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ApprovalGroupBy) sqlScan(ctx context.Context, root *ApprovalQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ApprovalSelect is the builder for selecting fields of Approval entities.
type ApprovalSelect struct {
	*ApprovalQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ApprovalSelect) Aggregate(fns ...AggregateFunc) *ApprovalSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ApprovalSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApprovalQuery, *ApprovalSelect](ctx, _s.ApprovalQuery, _s, _s.inters, v)
}

func (_s *ApprovalSelect) sqlScan(ctx context.Context, root *ApprovalQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
