// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/cluster"
	"github.com/whg517/fleet/internal/store/ent/environment"
	"github.com/whg517/fleet/internal/store/ent/organization"
	"github.com/whg517/fleet/internal/store/ent/predicate"
)

// ClusterUpdate is the builder for updating Cluster entities.
type ClusterUpdate struct {
	config
	hooks    []Hook
	mutation *ClusterMutation
}

// Where appends a list predicates to the ClusterUpdate builder.
func (_u *ClusterUpdate) Where(ps ...predicate.Cluster) *ClusterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *ClusterUpdate) SetOrgID(v string) *ClusterUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *ClusterUpdate) SetNillableOrgID(v *string) *ClusterUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *ClusterUpdate) ClearOrgID() *ClusterUpdate {
	_u.mutation.ClearOrgID()
	return _u
}

// SetName sets the "name" field.
func (_u *ClusterUpdate) SetName(v string) *ClusterUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClusterUpdate) SetNillableName(v *string) *ClusterUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIServer sets the "api_server" field.
func (_u *ClusterUpdate) SetAPIServer(v string) *ClusterUpdate {
	_u.mutation.SetAPIServer(v)
	return _u
}

// SetNillableAPIServer sets the "api_server" field if the given value is not nil.
func (_u *ClusterUpdate) SetNillableAPIServer(v *string) *ClusterUpdate {
	if v != nil {
		_u.SetAPIServer(*v)
	}
	return _u
}

// SetKubeconfigEncrypted sets the "kubeconfig_encrypted" field.
func (_u *ClusterUpdate) SetKubeconfigEncrypted(v []byte) *ClusterUpdate {
	_u.mutation.SetKubeconfigEncrypted(v)
	return _u
}

// ClearKubeconfigEncrypted clears the value of the "kubeconfig_encrypted" field.
func (_u *ClusterUpdate) ClearKubeconfigEncrypted() *ClusterUpdate {
	_u.mutation.ClearKubeconfigEncrypted()
	return _u
}

// SetLabels sets the "labels" field.
func (_u *ClusterUpdate) SetLabels(v map[string]string) *ClusterUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *ClusterUpdate) ClearLabels() *ClusterUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ClusterUpdate) SetStatus(v cluster.Status) *ClusterUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClusterUpdate) SetNillableStatus(v *cluster.Status) *ClusterUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClusterUpdate) SetUpdatedAt(v time.Time) *ClusterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEnvironmentIDs adds the "environments" edge to the Environment entity by IDs.
func (_u *ClusterUpdate) AddEnvironmentIDs(ids ...string) *ClusterUpdate {
	_u.mutation.AddEnvironmentIDs(ids...)
	return _u
}

// AddEnvironments adds the "environments" edges to the Environment entity.
func (_u *ClusterUpdate) AddEnvironments(v ...*Environment) *ClusterUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnvironmentIDs(ids...)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *ClusterUpdate) SetOrganizationID(id string) *ClusterUpdate {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *ClusterUpdate) SetNillableOrganizationID(id *string) *ClusterUpdate {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *ClusterUpdate) SetOrganization(v *Organization) *ClusterUpdate {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the ClusterMutation object of the builder.
func (_u *ClusterUpdate) Mutation() *ClusterMutation {
	return _u.mutation
}

// ClearEnvironments clears all "environments" edges to the Environment entity.
func (_u *ClusterUpdate) ClearEnvironments() *ClusterUpdate {
	_u.mutation.ClearEnvironments()
	return _u
}

// RemoveEnvironmentIDs removes the "environments" edge to Environment entities by IDs.
func (_u *ClusterUpdate) RemoveEnvironmentIDs(ids ...string) *ClusterUpdate {
	_u.mutation.RemoveEnvironmentIDs(ids...)
	return _u
}

// RemoveEnvironments removes "environments" edges to Environment entities.
func (_u *ClusterUpdate) RemoveEnvironments(v ...*Environment) *ClusterUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnvironmentIDs(ids...)
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *ClusterUpdate) ClearOrganization() *ClusterUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClusterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClusterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClusterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClusterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClusterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cluster.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClusterUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cluster.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Cluster.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIServer(); ok {
		if err := cluster.APIServerValidator(v); err != nil {
			return &ValidationError{Name: "api_server", err: fmt.Errorf(`ent: validator failed for field "Cluster.api_server": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := cluster.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Cluster.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ClusterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cluster.Table, cluster.Columns, sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cluster.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIServer(); ok {
		_spec.SetField(cluster.FieldAPIServer, field.TypeString, value)
	}
	if value, ok := _u.mutation.KubeconfigEncrypted(); ok {
		_spec.SetField(cluster.FieldKubeconfigEncrypted, field.TypeBytes, value)
	}
	if _u.mutation.KubeconfigEncryptedCleared() {
		_spec.ClearField(cluster.FieldKubeconfigEncrypted, field.TypeBytes)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(cluster.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(cluster.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cluster.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cluster.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cluster.EnvironmentsTable,
			Columns: []string{cluster.EnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnvironmentsIDs(); len(nodes) > 0 && !_u.mutation.EnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cluster.EnvironmentsTable,
			Columns: []string{cluster.EnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvironmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cluster.EnvironmentsTable,
			Columns: []string{cluster.EnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cluster.OrganizationTable,
			Columns: []string{cluster.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cluster.OrganizationTable,
			Columns: []string{cluster.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cluster.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClusterUpdateOne is the builder for updating a single Cluster entity.
type ClusterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClusterMutation
}

// SetOrgID sets the "org_id" field.
func (_u *ClusterUpdateOne) SetOrgID(v string) *ClusterUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *ClusterUpdateOne) SetNillableOrgID(v *string) *ClusterUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *ClusterUpdateOne) ClearOrgID() *ClusterUpdateOne {
	_u.mutation.ClearOrgID()
	return _u
}

// SetName sets the "name" field.
func (_u *ClusterUpdateOne) SetName(v string) *ClusterUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClusterUpdateOne) SetNillableName(v *string) *ClusterUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIServer sets the "api_server" field.
func (_u *ClusterUpdateOne) SetAPIServer(v string) *ClusterUpdateOne {
	_u.mutation.SetAPIServer(v)
	return _u
}

// SetNillableAPIServer sets the "api_server" field if the given value is not nil.
func (_u *ClusterUpdateOne) SetNillableAPIServer(v *string) *ClusterUpdateOne {
	if v != nil {
		_u.SetAPIServer(*v)
	}
	return _u
}

// SetKubeconfigEncrypted sets the "kubeconfig_encrypted" field.
func (_u *ClusterUpdateOne) SetKubeconfigEncrypted(v []byte) *ClusterUpdateOne {
	_u.mutation.SetKubeconfigEncrypted(v)
	return _u
}

// ClearKubeconfigEncrypted clears the value of the "kubeconfig_encrypted" field.
func (_u *ClusterUpdateOne) ClearKubeconfigEncrypted() *ClusterUpdateOne {
	_u.mutation.ClearKubeconfigEncrypted()
	return _u
}

// SetLabels sets the "labels" field.
func (_u *ClusterUpdateOne) SetLabels(v map[string]string) *ClusterUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *ClusterUpdateOne) ClearLabels() *ClusterUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ClusterUpdateOne) SetStatus(v cluster.Status) *ClusterUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClusterUpdateOne) SetNillableStatus(v *cluster.Status) *ClusterUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClusterUpdateOne) SetUpdatedAt(v time.Time) *ClusterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEnvironmentIDs adds the "environments" edge to the Environment entity by IDs.
func (_u *ClusterUpdateOne) AddEnvironmentIDs(ids ...string) *ClusterUpdateOne {
	_u.mutation.AddEnvironmentIDs(ids...)
	return _u
}

// AddEnvironments adds the "environments" edges to the Environment entity.
func (_u *ClusterUpdateOne) AddEnvironments(v ...*Environment) *ClusterUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnvironmentIDs(ids...)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *ClusterUpdateOne) SetOrganizationID(id string) *ClusterUpdateOne {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *ClusterUpdateOne) SetNillableOrganizationID(id *string) *ClusterUpdateOne {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *ClusterUpdateOne) SetOrganization(v *Organization) *ClusterUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the ClusterMutation object of the builder.
func (_u *ClusterUpdateOne) Mutation() *ClusterMutation {
	return _u.mutation
}

// ClearEnvironments clears all "environments" edges to the Environment entity.
func (_u *ClusterUpdateOne) ClearEnvironments() *ClusterUpdateOne {
	_u.mutation.ClearEnvironments()
	return _u
}

// RemoveEnvironmentIDs removes the "environments" edge to Environment entities by IDs.
func (_u *ClusterUpdateOne) RemoveEnvironmentIDs(ids ...string) *ClusterUpdateOne {
	_u.mutation.RemoveEnvironmentIDs(ids...)
	return _u
}

// RemoveEnvironments removes "environments" edges to Environment entities.
func (_u *ClusterUpdateOne) RemoveEnvironments(v ...*Environment) *ClusterUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnvironmentIDs(ids...)
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *ClusterUpdateOne) ClearOrganization() *ClusterUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// Where appends a list predicates to the ClusterUpdate builder.
func (_u *ClusterUpdateOne) Where(ps ...predicate.Cluster) *ClusterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClusterUpdateOne) Select(field string, fields ...string) *ClusterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Cluster entity.
func (_u *ClusterUpdateOne) Save(ctx context.Context) (*Cluster, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClusterUpdateOne) SaveX(ctx context.Context) *Cluster {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClusterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClusterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClusterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cluster.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClusterUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := cluster.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Cluster.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIServer(); ok {
		if err := cluster.APIServerValidator(v); err != nil {
			return &ValidationError{Name: "api_server", err: fmt.Errorf(`ent: validator failed for field "Cluster.api_server": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := cluster.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Cluster.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ClusterUpdateOne) sqlSave(ctx context.Context) (_node *Cluster, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cluster.Table, cluster.Columns, sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cluster.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cluster.FieldID)
		for _, f := range fields {
			if !cluster.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cluster.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(cluster.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIServer(); ok {
		_spec.SetField(cluster.FieldAPIServer, field.TypeString, value)
	}
	if value, ok := _u.mutation.KubeconfigEncrypted(); ok {
		_spec.SetField(cluster.FieldKubeconfigEncrypted, field.TypeBytes, value)
	}
	if _u.mutation.KubeconfigEncryptedCleared() {
		_spec.ClearField(cluster.FieldKubeconfigEncrypted, field.TypeBytes)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(cluster.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(cluster.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cluster.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cluster.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cluster.EnvironmentsTable,
			Columns: []string{cluster.EnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnvironmentsIDs(); len(nodes) > 0 && !_u.mutation.EnvironmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cluster.EnvironmentsTable,
			Columns: []string{cluster.EnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvironmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cluster.EnvironmentsTable,
			Columns: []string{cluster.EnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cluster.OrganizationTable,
			Columns: []string{cluster.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cluster.OrganizationTable,
			Columns: []string{cluster.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Cluster{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cluster.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
