// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/cluster"
	"github.com/whg517/fleet/internal/store/ent/environment"
	"github.com/whg517/fleet/internal/store/ent/organization"
)

// ClusterCreate is the builder for creating a Cluster entity.
type ClusterCreate struct {
	config
	mutation *ClusterMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *ClusterCreate) SetOrgID(v string) *ClusterCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_c *ClusterCreate) SetNillableOrgID(v *string) *ClusterCreate {
	if v != nil {
		_c.SetOrgID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ClusterCreate) SetName(v string) *ClusterCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAPIServer sets the "api_server" field.
func (_c *ClusterCreate) SetAPIServer(v string) *ClusterCreate {
	_c.mutation.SetAPIServer(v)
	return _c
}

// SetKubeconfigEncrypted sets the "kubeconfig_encrypted" field.
func (_c *ClusterCreate) SetKubeconfigEncrypted(v []byte) *ClusterCreate {
	_c.mutation.SetKubeconfigEncrypted(v)
	return _c
}

// SetLabels sets the "labels" field.
func (_c *ClusterCreate) SetLabels(v map[string]string) *ClusterCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ClusterCreate) SetStatus(v cluster.Status) *ClusterCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ClusterCreate) SetNillableStatus(v *cluster.Status) *ClusterCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ClusterCreate) SetCreatedAt(v time.Time) *ClusterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ClusterCreate) SetNillableCreatedAt(v *time.Time) *ClusterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ClusterCreate) SetUpdatedAt(v time.Time) *ClusterCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ClusterCreate) SetNillableUpdatedAt(v *time.Time) *ClusterCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ClusterCreate) SetID(v string) *ClusterCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddEnvironmentIDs adds the "environments" edge to the Environment entity by IDs.
func (_c *ClusterCreate) AddEnvironmentIDs(ids ...string) *ClusterCreate {
	_c.mutation.AddEnvironmentIDs(ids...)
	return _c
}

// AddEnvironments adds the "environments" edges to the Environment entity.
func (_c *ClusterCreate) AddEnvironments(v ...*Environment) *ClusterCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEnvironmentIDs(ids...)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_c *ClusterCreate) SetOrganizationID(id string) *ClusterCreate {
	_c.mutation.SetOrganizationID(id)
	return _c
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_c *ClusterCreate) SetNillableOrganizationID(id *string) *ClusterCreate {
	if id != nil {
		_c = _c.SetOrganizationID(*id)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *ClusterCreate) SetOrganization(v *Organization) *ClusterCreate {
	return _c.SetOrganizationID(v.ID)
}

// Mutation returns the ClusterMutation object of the builder.
func (_c *ClusterCreate) Mutation() *ClusterMutation {
	return _c.mutation
}

// Save creates the Cluster in the database.
func (_c *ClusterCreate) Save(ctx context.Context) (*Cluster, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClusterCreate) SaveX(ctx context.Context) *Cluster {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClusterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClusterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClusterCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := cluster.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cluster.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cluster.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClusterCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Cluster.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := cluster.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Cluster.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIServer(); !ok {
		return &ValidationError{Name: "api_server", err: errors.New(`ent: missing required field "Cluster.api_server"`)}
	}
	if v, ok := _c.mutation.APIServer(); ok {
		if err := cluster.APIServerValidator(v); err != nil {
			return &ValidationError{Name: "api_server", err: fmt.Errorf(`ent: validator failed for field "Cluster.api_server": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Cluster.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := cluster.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Cluster.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Cluster.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Cluster.updated_at"`)}
	}
	return nil
}

func (_c *ClusterCreate) sqlSave(ctx context.Context) (*Cluster, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Cluster.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClusterCreate) createSpec() (*Cluster, *sqlgraph.CreateSpec) {
	var (
		_node = &Cluster{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cluster.Table, sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(cluster.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.APIServer(); ok {
		_spec.SetField(cluster.FieldAPIServer, field.TypeString, value)
		_node.APIServer = value
	}
	if value, ok := _c.mutation.KubeconfigEncrypted(); ok {
		_spec.SetField(cluster.FieldKubeconfigEncrypted, field.TypeBytes, value)
		_node.KubeconfigEncrypted = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(cluster.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(cluster.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cluster.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cluster.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.EnvironmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cluster.EnvironmentsTable,
			Columns: []string{cluster.EnvironmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cluster.OrganizationTable,
			Columns: []string{cluster.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrgID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClusterCreateBulk is the builder for creating many Cluster entities in bulk.
type ClusterCreateBulk struct {
	config
	err      error
	builders []*ClusterCreate
}

// Save creates the Cluster entities in the database.
func (_c *ClusterCreateBulk) Save(ctx context.Context) ([]*Cluster, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Cluster, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClusterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClusterCreateBulk) SaveX(ctx context.Context) []*Cluster {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClusterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClusterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
