// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/configsnapshot"
	"github.com/whg517/fleet/internal/store/ent/environment"
	"github.com/whg517/fleet/internal/store/ent/organization"
	"github.com/whg517/fleet/internal/store/ent/predicate"
	"github.com/whg517/fleet/internal/store/ent/service"
)

// ConfigSnapshotUpdate is the builder for updating ConfigSnapshot entities.
type ConfigSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *ConfigSnapshotMutation
}

// Where appends a list predicates to the ConfigSnapshotUpdate builder.
func (_u *ConfigSnapshotUpdate) Where(ps ...predicate.ConfigSnapshot) *ConfigSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *ConfigSnapshotUpdate) SetOrgID(v string) *ConfigSnapshotUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *ConfigSnapshotUpdate) SetNillableOrgID(v *string) *ConfigSnapshotUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *ConfigSnapshotUpdate) ClearOrgID() *ConfigSnapshotUpdate {
	_u.mutation.ClearOrgID()
	return _u
}

// SetServiceID sets the "service_id" field.
func (_u *ConfigSnapshotUpdate) SetServiceID(v string) *ConfigSnapshotUpdate {
	_u.mutation.SetServiceID(v)
	return _u
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (_u *ConfigSnapshotUpdate) SetNillableServiceID(v *string) *ConfigSnapshotUpdate {
	if v != nil {
		_u.SetServiceID(*v)
	}
	return _u
}

// SetEnvironmentID sets the "environment_id" field.
func (_u *ConfigSnapshotUpdate) SetEnvironmentID(v string) *ConfigSnapshotUpdate {
	_u.mutation.SetEnvironmentID(v)
	return _u
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_u *ConfigSnapshotUpdate) SetNillableEnvironmentID(v *string) *ConfigSnapshotUpdate {
	if v != nil {
		_u.SetEnvironmentID(*v)
	}
	return _u
}

// SetValues sets the "values" field.
func (_u *ConfigSnapshotUpdate) SetValues(v map[string]interface{}) *ConfigSnapshotUpdate {
	_u.mutation.SetValues(v)
	return _u
}

// ClearValues clears the value of the "values" field.
func (_u *ConfigSnapshotUpdate) ClearValues() *ConfigSnapshotUpdate {
	_u.mutation.ClearValues()
	return _u
}

// SetPreviousValues sets the "previous_values" field.
func (_u *ConfigSnapshotUpdate) SetPreviousValues(v map[string]interface{}) *ConfigSnapshotUpdate {
	_u.mutation.SetPreviousValues(v)
	return _u
}

// ClearPreviousValues clears the value of the "previous_values" field.
func (_u *ConfigSnapshotUpdate) ClearPreviousValues() *ConfigSnapshotUpdate {
	_u.mutation.ClearPreviousValues()
	return _u
}

// SetChangedBy sets the "changed_by" field.
func (_u *ConfigSnapshotUpdate) SetChangedBy(v string) *ConfigSnapshotUpdate {
	_u.mutation.SetChangedBy(v)
	return _u
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (_u *ConfigSnapshotUpdate) SetNillableChangedBy(v *string) *ConfigSnapshotUpdate {
	if v != nil {
		_u.SetChangedBy(*v)
	}
	return _u
}

// ClearChangedBy clears the value of the "changed_by" field.
func (_u *ConfigSnapshotUpdate) ClearChangedBy() *ConfigSnapshotUpdate {
	_u.mutation.ClearChangedBy()
	return _u
}

// SetChangeReason sets the "change_reason" field.
func (_u *ConfigSnapshotUpdate) SetChangeReason(v string) *ConfigSnapshotUpdate {
	_u.mutation.SetChangeReason(v)
	return _u
}

// SetNillableChangeReason sets the "change_reason" field if the given value is not nil.
func (_u *ConfigSnapshotUpdate) SetNillableChangeReason(v *string) *ConfigSnapshotUpdate {
	if v != nil {
		_u.SetChangeReason(*v)
	}
	return _u
}

// ClearChangeReason clears the value of the "change_reason" field.
func (_u *ConfigSnapshotUpdate) ClearChangeReason() *ConfigSnapshotUpdate {
	_u.mutation.ClearChangeReason()
	return _u
}

// SetService sets the "service" edge to the Service entity.
func (_u *ConfigSnapshotUpdate) SetService(v *Service) *ConfigSnapshotUpdate {
	return _u.SetServiceID(v.ID)
}

// SetEnvironment sets the "environment" edge to the Environment entity.
func (_u *ConfigSnapshotUpdate) SetEnvironment(v *Environment) *ConfigSnapshotUpdate {
	return _u.SetEnvironmentID(v.ID)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *ConfigSnapshotUpdate) SetOrganizationID(id string) *ConfigSnapshotUpdate {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *ConfigSnapshotUpdate) SetNillableOrganizationID(id *string) *ConfigSnapshotUpdate {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *ConfigSnapshotUpdate) SetOrganization(v *Organization) *ConfigSnapshotUpdate {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the ConfigSnapshotMutation object of the builder.
func (_u *ConfigSnapshotUpdate) Mutation() *ConfigSnapshotMutation {
	return _u.mutation
}

// ClearService clears the "service" edge to the Service entity.
func (_u *ConfigSnapshotUpdate) ClearService() *ConfigSnapshotUpdate {
	_u.mutation.ClearService()
	return _u
}

// ClearEnvironment clears the "environment" edge to the Environment entity.
func (_u *ConfigSnapshotUpdate) ClearEnvironment() *ConfigSnapshotUpdate {
	_u.mutation.ClearEnvironment()
	return _u
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *ConfigSnapshotUpdate) ClearOrganization() *ConfigSnapshotUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfigSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfigSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigSnapshotUpdate) check() error {
	if v, ok := _u.mutation.ServiceID(); ok {
		if err := configsnapshot.ServiceIDValidator(v); err != nil {
			return &ValidationError{Name: "service_id", err: fmt.Errorf(`ent: validator failed for field "ConfigSnapshot.service_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnvironmentID(); ok {
		if err := configsnapshot.EnvironmentIDValidator(v); err != nil {
			return &ValidationError{Name: "environment_id", err: fmt.Errorf(`ent: validator failed for field "ConfigSnapshot.environment_id": %w`, err)}
		}
	}
	if _u.mutation.ServiceCleared() && len(_u.mutation.ServiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConfigSnapshot.service"`)
	}
	if _u.mutation.EnvironmentCleared() && len(_u.mutation.EnvironmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConfigSnapshot.environment"`)
	}
	return nil
}

func (_u *ConfigSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configsnapshot.Table, configsnapshot.Columns, sqlgraph.NewFieldSpec(configsnapshot.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Values(); ok {
		_spec.SetField(configsnapshot.FieldValues, field.TypeJSON, value)
	}
	if _u.mutation.ValuesCleared() {
		_spec.ClearField(configsnapshot.FieldValues, field.TypeJSON)
	}
	if value, ok := _u.mutation.PreviousValues(); ok {
		_spec.SetField(configsnapshot.FieldPreviousValues, field.TypeJSON, value)
	}
	if _u.mutation.PreviousValuesCleared() {
		_spec.ClearField(configsnapshot.FieldPreviousValues, field.TypeJSON)
	}
	if value, ok := _u.mutation.ChangedBy(); ok {
		_spec.SetField(configsnapshot.FieldChangedBy, field.TypeString, value)
	}
	if _u.mutation.ChangedByCleared() {
		_spec.ClearField(configsnapshot.FieldChangedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ChangeReason(); ok {
		_spec.SetField(configsnapshot.FieldChangeReason, field.TypeString, value)
	}
	if _u.mutation.ChangeReasonCleared() {
		_spec.ClearField(configsnapshot.FieldChangeReason, field.TypeString)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.ServiceTable,
			Columns: []string{configsnapshot.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.ServiceTable,
			Columns: []string{configsnapshot.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.EnvironmentTable,
			Columns: []string{configsnapshot.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.EnvironmentTable,
			Columns: []string{configsnapshot.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.OrganizationTable,
			Columns: []string{configsnapshot.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.OrganizationTable,
			Columns: []string{configsnapshot.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfigSnapshotUpdateOne is the builder for updating a single ConfigSnapshot entity.
type ConfigSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConfigSnapshotMutation
}

// SetOrgID sets the "org_id" field.
func (_u *ConfigSnapshotUpdateOne) SetOrgID(v string) *ConfigSnapshotUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *ConfigSnapshotUpdateOne) SetNillableOrgID(v *string) *ConfigSnapshotUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *ConfigSnapshotUpdateOne) ClearOrgID() *ConfigSnapshotUpdateOne {
	_u.mutation.ClearOrgID()
	return _u
}

// SetServiceID sets the "service_id" field.
func (_u *ConfigSnapshotUpdateOne) SetServiceID(v string) *ConfigSnapshotUpdateOne {
	_u.mutation.SetServiceID(v)
	return _u
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (_u *ConfigSnapshotUpdateOne) SetNillableServiceID(v *string) *ConfigSnapshotUpdateOne {
	if v != nil {
		_u.SetServiceID(*v)
	}
	return _u
}

// SetEnvironmentID sets the "environment_id" field.
func (_u *ConfigSnapshotUpdateOne) SetEnvironmentID(v string) *ConfigSnapshotUpdateOne {
	_u.mutation.SetEnvironmentID(v)
	return _u
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_u *ConfigSnapshotUpdateOne) SetNillableEnvironmentID(v *string) *ConfigSnapshotUpdateOne {
	if v != nil {
		_u.SetEnvironmentID(*v)
	}
	return _u
}

// SetValues sets the "values" field.
func (_u *ConfigSnapshotUpdateOne) SetValues(v map[string]interface{}) *ConfigSnapshotUpdateOne {
	_u.mutation.SetValues(v)
	return _u
}

// ClearValues clears the value of the "values" field.
func (_u *ConfigSnapshotUpdateOne) ClearValues() *ConfigSnapshotUpdateOne {
	_u.mutation.ClearValues()
	return _u
}

// SetPreviousValues sets the "previous_values" field.
func (_u *ConfigSnapshotUpdateOne) SetPreviousValues(v map[string]interface{}) *ConfigSnapshotUpdateOne {
	_u.mutation.SetPreviousValues(v)
	return _u
}

// ClearPreviousValues clears the value of the "previous_values" field.
func (_u *ConfigSnapshotUpdateOne) ClearPreviousValues() *ConfigSnapshotUpdateOne {
	_u.mutation.ClearPreviousValues()
	return _u
}

// SetChangedBy sets the "changed_by" field.
func (_u *ConfigSnapshotUpdateOne) SetChangedBy(v string) *ConfigSnapshotUpdateOne {
	_u.mutation.SetChangedBy(v)
	return _u
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (_u *ConfigSnapshotUpdateOne) SetNillableChangedBy(v *string) *ConfigSnapshotUpdateOne {
	if v != nil {
		_u.SetChangedBy(*v)
	}
	return _u
}

// ClearChangedBy clears the value of the "changed_by" field.
func (_u *ConfigSnapshotUpdateOne) ClearChangedBy() *ConfigSnapshotUpdateOne {
	_u.mutation.ClearChangedBy()
	return _u
}

// SetChangeReason sets the "change_reason" field.
func (_u *ConfigSnapshotUpdateOne) SetChangeReason(v string) *ConfigSnapshotUpdateOne {
	_u.mutation.SetChangeReason(v)
	return _u
}

// SetNillableChangeReason sets the "change_reason" field if the given value is not nil.
func (_u *ConfigSnapshotUpdateOne) SetNillableChangeReason(v *string) *ConfigSnapshotUpdateOne {
	if v != nil {
		_u.SetChangeReason(*v)
	}
	return _u
}

// ClearChangeReason clears the value of the "change_reason" field.
func (_u *ConfigSnapshotUpdateOne) ClearChangeReason() *ConfigSnapshotUpdateOne {
	_u.mutation.ClearChangeReason()
	return _u
}

// SetService sets the "service" edge to the Service entity.
func (_u *ConfigSnapshotUpdateOne) SetService(v *Service) *ConfigSnapshotUpdateOne {
	return _u.SetServiceID(v.ID)
}

// SetEnvironment sets the "environment" edge to the Environment entity.
func (_u *ConfigSnapshotUpdateOne) SetEnvironment(v *Environment) *ConfigSnapshotUpdateOne {
	return _u.SetEnvironmentID(v.ID)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *ConfigSnapshotUpdateOne) SetOrganizationID(id string) *ConfigSnapshotUpdateOne {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *ConfigSnapshotUpdateOne) SetNillableOrganizationID(id *string) *ConfigSnapshotUpdateOne {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *ConfigSnapshotUpdateOne) SetOrganization(v *Organization) *ConfigSnapshotUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the ConfigSnapshotMutation object of the builder.
func (_u *ConfigSnapshotUpdateOne) Mutation() *ConfigSnapshotMutation {
	return _u.mutation
}

// ClearService clears the "service" edge to the Service entity.
func (_u *ConfigSnapshotUpdateOne) ClearService() *ConfigSnapshotUpdateOne {
	_u.mutation.ClearService()
	return _u
}

// ClearEnvironment clears the "environment" edge to the Environment entity.
func (_u *ConfigSnapshotUpdateOne) ClearEnvironment() *ConfigSnapshotUpdateOne {
	_u.mutation.ClearEnvironment()
	return _u
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *ConfigSnapshotUpdateOne) ClearOrganization() *ConfigSnapshotUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// Where appends a list predicates to the ConfigSnapshotUpdate builder.
func (_u *ConfigSnapshotUpdateOne) Where(ps ...predicate.ConfigSnapshot) *ConfigSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfigSnapshotUpdateOne) Select(field string, fields ...string) *ConfigSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConfigSnapshot entity.
func (_u *ConfigSnapshotUpdateOne) Save(ctx context.Context) (*ConfigSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigSnapshotUpdateOne) SaveX(ctx context.Context) *ConfigSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfigSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.ServiceID(); ok {
		if err := configsnapshot.ServiceIDValidator(v); err != nil {
			return &ValidationError{Name: "service_id", err: fmt.Errorf(`ent: validator failed for field "ConfigSnapshot.service_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnvironmentID(); ok {
		if err := configsnapshot.EnvironmentIDValidator(v); err != nil {
			return &ValidationError{Name: "environment_id", err: fmt.Errorf(`ent: validator failed for field "ConfigSnapshot.environment_id": %w`, err)}
		}
	}
	if _u.mutation.ServiceCleared() && len(_u.mutation.ServiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConfigSnapshot.service"`)
	}
	if _u.mutation.EnvironmentCleared() && len(_u.mutation.EnvironmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConfigSnapshot.environment"`)
	}
	return nil
}

func (_u *ConfigSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *ConfigSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configsnapshot.Table, configsnapshot.Columns, sqlgraph.NewFieldSpec(configsnapshot.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConfigSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configsnapshot.FieldID)
		for _, f := range fields {
			if !configsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != configsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Values(); ok {
		_spec.SetField(configsnapshot.FieldValues, field.TypeJSON, value)
	}
	if _u.mutation.ValuesCleared() {
		_spec.ClearField(configsnapshot.FieldValues, field.TypeJSON)
	}
	if value, ok := _u.mutation.PreviousValues(); ok {
		_spec.SetField(configsnapshot.FieldPreviousValues, field.TypeJSON, value)
	}
	if _u.mutation.PreviousValuesCleared() {
		_spec.ClearField(configsnapshot.FieldPreviousValues, field.TypeJSON)
	}
	if value, ok := _u.mutation.ChangedBy(); ok {
		_spec.SetField(configsnapshot.FieldChangedBy, field.TypeString, value)
	}
	if _u.mutation.ChangedByCleared() {
		_spec.ClearField(configsnapshot.FieldChangedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ChangeReason(); ok {
		_spec.SetField(configsnapshot.FieldChangeReason, field.TypeString, value)
	}
	if _u.mutation.ChangeReasonCleared() {
		_spec.ClearField(configsnapshot.FieldChangeReason, field.TypeString)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.ServiceTable,
			Columns: []string{configsnapshot.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.ServiceTable,
			Columns: []string{configsnapshot.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.EnvironmentTable,
			Columns: []string{configsnapshot.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.EnvironmentTable,
			Columns: []string{configsnapshot.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.OrganizationTable,
			Columns: []string{configsnapshot.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configsnapshot.OrganizationTable,
			Columns: []string{configsnapshot.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ConfigSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
