// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/whg517/fleet/internal/store/ent/cluster"
	"github.com/whg517/fleet/internal/store/ent/deployment"
	"github.com/whg517/fleet/internal/store/ent/environment"
	"github.com/whg517/fleet/internal/store/ent/organization"
	"github.com/whg517/fleet/internal/store/ent/service"
)

// Deployment is the model entity for the Deployment schema.
type Deployment struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OrgID holds the value of the "org_id" field.
	OrgID string `json:"org_id,omitempty"`
	// ServiceID holds the value of the "service_id" field.
	ServiceID string `json:"service_id,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// ClusterID holds the value of the "cluster_id" field.
	ClusterID string `json:"cluster_id,omitempty"`
	// TemplateVersionID holds the value of the "template_version_id" field.
	TemplateVersionID string `json:"template_version_id,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// ValuesOverride holds the value of the "values_override" field.
	ValuesOverride map[string]interface{} `json:"values_override,omitempty"`
	// Status holds the value of the "status" field.
	Status deployment.Status `json:"status,omitempty"`
	// ArgocdAppName holds the value of the "argocd_app_name" field.
	ArgocdAppName string `json:"argocd_app_name,omitempty"`
	// SyncStatus holds the value of the "sync_status" field.
	SyncStatus string `json:"sync_status,omitempty"`
	// HealthStatus holds the value of the "health_status" field.
	HealthStatus string `json:"health_status,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeploymentQuery when eager-loading is set.
	Edges        DeploymentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeploymentEdges holds the relations/edges for other nodes in the graph.
type DeploymentEdges struct {
	// Service holds the value of the service edge.
	Service *Service `json:"service,omitempty"`
	// Environment holds the value of the environment edge.
	Environment *Environment `json:"environment,omitempty"`
	// Cluster holds the value of the cluster edge.
	Cluster *Cluster `json:"cluster,omitempty"`
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// Approvals holds the value of the approvals edge.
	Approvals []*Approval `json:"approvals,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// ServiceOrErr returns the Service value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeploymentEdges) ServiceOrErr() (*Service, error) {
	if e.Service != nil {
		return e.Service, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: service.Label}
	}
	return nil, &NotLoadedError{edge: "service"}
}

// EnvironmentOrErr returns the Environment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeploymentEdges) EnvironmentOrErr() (*Environment, error) {
	if e.Environment != nil {
		return e.Environment, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: environment.Label}
	}
	return nil, &NotLoadedError{edge: "environment"}
}

// ClusterOrErr returns the Cluster value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeploymentEdges) ClusterOrErr() (*Cluster, error) {
	if e.Cluster != nil {
		return e.Cluster, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: cluster.Label}
	}
	return nil, &NotLoadedError{edge: "cluster"}
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeploymentEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// ApprovalsOrErr returns the Approvals value or an error if the edge
// was not loaded in eager-loading.
func (e DeploymentEdges) ApprovalsOrErr() ([]*Approval, error) {
	if e.loadedTypes[4] {
		return e.Approvals, nil
	}
	return nil, &NotLoadedError{edge: "approvals"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Deployment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deployment.FieldValuesOverride:
			values[i] = new([]byte)
		case deployment.FieldID, deployment.FieldOrgID, deployment.FieldServiceID, deployment.FieldEnvironmentID, deployment.FieldClusterID, deployment.FieldTemplateVersionID, deployment.FieldVersion, deployment.FieldStatus, deployment.FieldArgocdAppName, deployment.FieldSyncStatus, deployment.FieldHealthStatus, deployment.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case deployment.FieldCreatedAt, deployment.FieldUpdatedAt, deployment.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Deployment fields.
func (_m *Deployment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deployment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case deployment.FieldOrgID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value.Valid {
				_m.OrgID = value.String
			}
		case deployment.FieldServiceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_id", values[i])
			} else if value.Valid {
				_m.ServiceID = value.String
			}
		case deployment.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				_m.EnvironmentID = value.String
			}
		case deployment.FieldClusterID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cluster_id", values[i])
			} else if value.Valid {
				_m.ClusterID = value.String
			}
		case deployment.FieldTemplateVersionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_version_id", values[i])
			} else if value.Valid {
				_m.TemplateVersionID = value.String
			}
		case deployment.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case deployment.FieldValuesOverride:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field values_override", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ValuesOverride); err != nil {
					return fmt.Errorf("unmarshal field values_override: %w", err)
				}
			}
		case deployment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = deployment.Status(value.String)
			}
		case deployment.FieldArgocdAppName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field argocd_app_name", values[i])
			} else if value.Valid {
				_m.ArgocdAppName = value.String
			}
		case deployment.FieldSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_status", values[i])
			} else if value.Valid {
				_m.SyncStatus = value.String
			}
		case deployment.FieldHealthStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field health_status", values[i])
			} else if value.Valid {
				_m.HealthStatus = value.String
			}
		case deployment.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case deployment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case deployment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case deployment.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Deployment.
// This includes values selected through modifiers, order, etc.
func (_m *Deployment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryService queries the "service" edge of the Deployment entity.
func (_m *Deployment) QueryService() *ServiceQuery {
	return NewDeploymentClient(_m.config).QueryService(_m)
}

// QueryEnvironment queries the "environment" edge of the Deployment entity.
func (_m *Deployment) QueryEnvironment() *EnvironmentQuery {
	return NewDeploymentClient(_m.config).QueryEnvironment(_m)
}

// QueryCluster queries the "cluster" edge of the Deployment entity.
func (_m *Deployment) QueryCluster() *ClusterQuery {
	return NewDeploymentClient(_m.config).QueryCluster(_m)
}

// QueryOrganization queries the "organization" edge of the Deployment entity.
func (_m *Deployment) QueryOrganization() *OrganizationQuery {
	return NewDeploymentClient(_m.config).QueryOrganization(_m)
}

// QueryApprovals queries the "approvals" edge of the Deployment entity.
func (_m *Deployment) QueryApprovals() *ApprovalQuery {
	return NewDeploymentClient(_m.config).QueryApprovals(_m)
}

// Update returns a builder for updating this Deployment.
// Note that you need to call Deployment.Unwrap() before calling this method if this Deployment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Deployment) Update() *DeploymentUpdateOne {
	return NewDeploymentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Deployment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Deployment) Unwrap() *Deployment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Deployment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Deployment) String() string {
	var builder strings.Builder
	builder.WriteString("Deployment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("org_id=")
	builder.WriteString(_m.OrgID)
	builder.WriteString(", ")
	builder.WriteString("service_id=")
	builder.WriteString(_m.ServiceID)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(_m.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("cluster_id=")
	builder.WriteString(_m.ClusterID)
	builder.WriteString(", ")
	builder.WriteString("template_version_id=")
	builder.WriteString(_m.TemplateVersionID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("values_override=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValuesOverride))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("argocd_app_name=")
	builder.WriteString(_m.ArgocdAppName)
	builder.WriteString(", ")
	builder.WriteString("sync_status=")
	builder.WriteString(_m.SyncStatus)
	builder.WriteString(", ")
	builder.WriteString("health_status=")
	builder.WriteString(_m.HealthStatus)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Deployments is a parsable slice of Deployment.
type Deployments []*Deployment
