// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/cluster"
	"github.com/whg517/fleet/internal/store/ent/deployment"
	"github.com/whg517/fleet/internal/store/ent/environment"
	"github.com/whg517/fleet/internal/store/ent/organization"
	"github.com/whg517/fleet/internal/store/ent/service"
)

// DeploymentCreate is the builder for creating a Deployment entity.
type DeploymentCreate struct {
	config
	mutation *DeploymentMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *DeploymentCreate) SetOrgID(v string) *DeploymentCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableOrgID(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetOrgID(*v)
	}
	return _c
}

// SetServiceID sets the "service_id" field.
func (_c *DeploymentCreate) SetServiceID(v string) *DeploymentCreate {
	_c.mutation.SetServiceID(v)
	return _c
}

// SetEnvironmentID sets the "environment_id" field.
func (_c *DeploymentCreate) SetEnvironmentID(v string) *DeploymentCreate {
	_c.mutation.SetEnvironmentID(v)
	return _c
}

// SetClusterID sets the "cluster_id" field.
func (_c *DeploymentCreate) SetClusterID(v string) *DeploymentCreate {
	_c.mutation.SetClusterID(v)
	return _c
}

// SetTemplateVersionID sets the "template_version_id" field.
func (_c *DeploymentCreate) SetTemplateVersionID(v string) *DeploymentCreate {
	_c.mutation.SetTemplateVersionID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *DeploymentCreate) SetVersion(v string) *DeploymentCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetValuesOverride sets the "values_override" field.
func (_c *DeploymentCreate) SetValuesOverride(v map[string]interface{}) *DeploymentCreate {
	_c.mutation.SetValuesOverride(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DeploymentCreate) SetStatus(v deployment.Status) *DeploymentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableStatus(v *deployment.Status) *DeploymentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetArgocdAppName sets the "argocd_app_name" field.
func (_c *DeploymentCreate) SetArgocdAppName(v string) *DeploymentCreate {
	_c.mutation.SetArgocdAppName(v)
	return _c
}

// SetNillableArgocdAppName sets the "argocd_app_name" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableArgocdAppName(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetArgocdAppName(*v)
	}
	return _c
}

// SetSyncStatus sets the "sync_status" field.
func (_c *DeploymentCreate) SetSyncStatus(v string) *DeploymentCreate {
	_c.mutation.SetSyncStatus(v)
	return _c
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableSyncStatus(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetSyncStatus(*v)
	}
	return _c
}

// SetHealthStatus sets the "health_status" field.
func (_c *DeploymentCreate) SetHealthStatus(v string) *DeploymentCreate {
	_c.mutation.SetHealthStatus(v)
	return _c
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableHealthStatus(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetHealthStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DeploymentCreate) SetCreatedBy(v string) *DeploymentCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableCreatedBy(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeploymentCreate) SetCreatedAt(v time.Time) *DeploymentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableCreatedAt(v *time.Time) *DeploymentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeploymentCreate) SetUpdatedAt(v time.Time) *DeploymentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableUpdatedAt(v *time.Time) *DeploymentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *DeploymentCreate) SetCompletedAt(v time.Time) *DeploymentCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableCompletedAt(v *time.Time) *DeploymentCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeploymentCreate) SetID(v string) *DeploymentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetService sets the "service" edge to the Service entity.
func (_c *DeploymentCreate) SetService(v *Service) *DeploymentCreate {
	return _c.SetServiceID(v.ID)
}

// SetEnvironment sets the "environment" edge to the Environment entity.
func (_c *DeploymentCreate) SetEnvironment(v *Environment) *DeploymentCreate {
	return _c.SetEnvironmentID(v.ID)
}

// SetCluster sets the "cluster" edge to the Cluster entity.
func (_c *DeploymentCreate) SetCluster(v *Cluster) *DeploymentCreate {
	return _c.SetClusterID(v.ID)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_c *DeploymentCreate) SetOrganizationID(id string) *DeploymentCreate {
	_c.mutation.SetOrganizationID(id)
	return _c
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_c *DeploymentCreate) SetNillableOrganizationID(id *string) *DeploymentCreate {
	if id != nil {
		_c = _c.SetOrganizationID(*id)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *DeploymentCreate) SetOrganization(v *Organization) *DeploymentCreate {
	return _c.SetOrganizationID(v.ID)
}

// Mutation returns the DeploymentMutation object of the builder.
func (_c *DeploymentCreate) Mutation() *DeploymentMutation {
	return _c.mutation
}

// Save creates the Deployment in the database.
func (_c *DeploymentCreate) Save(ctx context.Context) (*Deployment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeploymentCreate) SaveX(ctx context.Context) *Deployment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeploymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeploymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeploymentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := deployment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deployment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := deployment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeploymentCreate) check() error {
	if _, ok := _c.mutation.ServiceID(); !ok {
		return &ValidationError{Name: "service_id", err: errors.New(`ent: missing required field "Deployment.service_id"`)}
	}
	if v, ok := _c.mutation.ServiceID(); ok {
		if err := deployment.ServiceIDValidator(v); err != nil {
			return &ValidationError{Name: "service_id", err: fmt.Errorf(`ent: validator failed for field "Deployment.service_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EnvironmentID(); !ok {
		return &ValidationError{Name: "environment_id", err: errors.New(`ent: missing required field "Deployment.environment_id"`)}
	}
	if v, ok := _c.mutation.EnvironmentID(); ok {
		if err := deployment.EnvironmentIDValidator(v); err != nil {
			return &ValidationError{Name: "environment_id", err: fmt.Errorf(`ent: validator failed for field "Deployment.environment_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClusterID(); !ok {
		return &ValidationError{Name: "cluster_id", err: errors.New(`ent: missing required field "Deployment.cluster_id"`)}
	}
	if v, ok := _c.mutation.ClusterID(); ok {
		if err := deployment.ClusterIDValidator(v); err != nil {
			return &ValidationError{Name: "cluster_id", err: fmt.Errorf(`ent: validator failed for field "Deployment.cluster_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TemplateVersionID(); !ok {
		return &ValidationError{Name: "template_version_id", err: errors.New(`ent: missing required field "Deployment.template_version_id"`)}
	}
	if v, ok := _c.mutation.TemplateVersionID(); ok {
		if err := deployment.TemplateVersionIDValidator(v); err != nil {
			return &ValidationError{Name: "template_version_id", err: fmt.Errorf(`ent: validator failed for field "Deployment.template_version_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Deployment.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := deployment.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Deployment.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Deployment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := deployment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Deployment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Deployment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Deployment.updated_at"`)}
	}
	if len(_c.mutation.ServiceIDs()) == 0 {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required edge "Deployment.service"`)}
	}
	if len(_c.mutation.EnvironmentIDs()) == 0 {
		return &ValidationError{Name: "environment", err: errors.New(`ent: missing required edge "Deployment.environment"`)}
	}
	if len(_c.mutation.ClusterIDs()) == 0 {
		return &ValidationError{Name: "cluster", err: errors.New(`ent: missing required edge "Deployment.cluster"`)}
	}
	return nil
}

func (_c *DeploymentCreate) sqlSave(ctx context.Context) (*Deployment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Deployment.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeploymentCreate) createSpec() (*Deployment, *sqlgraph.CreateSpec) {
	var (
		_node = &Deployment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deployment.Table, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TemplateVersionID(); ok {
		_spec.SetField(deployment.FieldTemplateVersionID, field.TypeString, value)
		_node.TemplateVersionID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(deployment.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.ValuesOverride(); ok {
		_spec.SetField(deployment.FieldValuesOverride, field.TypeJSON, value)
		_node.ValuesOverride = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(deployment.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ArgocdAppName(); ok {
		_spec.SetField(deployment.FieldArgocdAppName, field.TypeString, value)
		_node.ArgocdAppName = value
	}
	if value, ok := _c.mutation.SyncStatus(); ok {
		_spec.SetField(deployment.FieldSyncStatus, field.TypeString, value)
		_node.SyncStatus = value
	}
	if value, ok := _c.mutation.HealthStatus(); ok {
		_spec.SetField(deployment.FieldHealthStatus, field.TypeString, value)
		_node.HealthStatus = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(deployment.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deployment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(deployment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(deployment.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if nodes := _c.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployment.ServiceTable,
			Columns: []string{deployment.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ServiceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployment.EnvironmentTable,
			Columns: []string{deployment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EnvironmentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClusterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployment.ClusterTable,
			Columns: []string{deployment.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClusterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployment.OrganizationTable,
			Columns: []string{deployment.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrgID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeploymentCreateBulk is the builder for creating many Deployment entities in bulk.
type DeploymentCreateBulk struct {
	config
	err      error
	builders []*DeploymentCreate
}

// Save creates the Deployment entities in the database.
func (_c *DeploymentCreateBulk) Save(ctx context.Context) ([]*Deployment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Deployment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeploymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeploymentCreateBulk) SaveX(ctx context.Context) []*Deployment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeploymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeploymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
