// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/cluster"
	"github.com/whg517/fleet/internal/store/ent/environment"
	"github.com/whg517/fleet/internal/store/ent/organization"
)

// EnvironmentCreate is the builder for creating a Environment entity.
type EnvironmentCreate struct {
	config
	mutation *EnvironmentMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *EnvironmentCreate) SetOrgID(v string) *EnvironmentCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableOrgID(v *string) *EnvironmentCreate {
	if v != nil {
		_c.SetOrgID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *EnvironmentCreate) SetName(v environment.Name) *EnvironmentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetClusterID sets the "cluster_id" field.
func (_c *EnvironmentCreate) SetClusterID(v string) *EnvironmentCreate {
	_c.mutation.SetClusterID(v)
	return _c
}

// SetNillableClusterID sets the "cluster_id" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableClusterID(v *string) *EnvironmentCreate {
	if v != nil {
		_c.SetClusterID(*v)
	}
	return _c
}

// SetNamespacePattern sets the "namespace_pattern" field.
func (_c *EnvironmentCreate) SetNamespacePattern(v string) *EnvironmentCreate {
	_c.mutation.SetNamespacePattern(v)
	return _c
}

// SetNillableNamespacePattern sets the "namespace_pattern" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableNamespacePattern(v *string) *EnvironmentCreate {
	if v != nil {
		_c.SetNamespacePattern(*v)
	}
	return _c
}

// SetApprovalRequired sets the "approval_required" field.
func (_c *EnvironmentCreate) SetApprovalRequired(v bool) *EnvironmentCreate {
	_c.mutation.SetApprovalRequired(v)
	return _c
}

// SetNillableApprovalRequired sets the "approval_required" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableApprovalRequired(v *bool) *EnvironmentCreate {
	if v != nil {
		_c.SetApprovalRequired(*v)
	}
	return _c
}

// SetApproverRole sets the "approver_role" field.
func (_c *EnvironmentCreate) SetApproverRole(v string) *EnvironmentCreate {
	_c.mutation.SetApproverRole(v)
	return _c
}

// SetNillableApproverRole sets the "approver_role" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableApproverRole(v *string) *EnvironmentCreate {
	if v != nil {
		_c.SetApproverRole(*v)
	}
	return _c
}

// SetConfigOverrides sets the "config_overrides" field.
func (_c *EnvironmentCreate) SetConfigOverrides(v map[string]interface{}) *EnvironmentCreate {
	_c.mutation.SetConfigOverrides(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnvironmentCreate) SetCreatedAt(v time.Time) *EnvironmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableCreatedAt(v *time.Time) *EnvironmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnvironmentCreate) SetUpdatedAt(v time.Time) *EnvironmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableUpdatedAt(v *time.Time) *EnvironmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EnvironmentCreate) SetID(v string) *EnvironmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCluster sets the "cluster" edge to the Cluster entity.
func (_c *EnvironmentCreate) SetCluster(v *Cluster) *EnvironmentCreate {
	return _c.SetClusterID(v.ID)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_c *EnvironmentCreate) SetOrganizationID(id string) *EnvironmentCreate {
	_c.mutation.SetOrganizationID(id)
	return _c
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableOrganizationID(id *string) *EnvironmentCreate {
	if id != nil {
		_c = _c.SetOrganizationID(*id)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *EnvironmentCreate) SetOrganization(v *Organization) *EnvironmentCreate {
	return _c.SetOrganizationID(v.ID)
}

// Mutation returns the EnvironmentMutation object of the builder.
func (_c *EnvironmentCreate) Mutation() *EnvironmentMutation {
	return _c.mutation
}

// Save creates the Environment in the database.
func (_c *EnvironmentCreate) Save(ctx context.Context) (*Environment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnvironmentCreate) SaveX(ctx context.Context) *Environment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvironmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvironmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnvironmentCreate) defaults() {
	if _, ok := _c.mutation.ApprovalRequired(); !ok {
		v := environment.DefaultApprovalRequired
		_c.mutation.SetApprovalRequired(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := environment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := environment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnvironmentCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Environment.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := environment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Environment.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ApprovalRequired(); !ok {
		return &ValidationError{Name: "approval_required", err: errors.New(`ent: missing required field "Environment.approval_required"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Environment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Environment.updated_at"`)}
	}
	return nil
}

func (_c *EnvironmentCreate) sqlSave(ctx context.Context) (*Environment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Environment.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnvironmentCreate) createSpec() (*Environment, *sqlgraph.CreateSpec) {
	var (
		_node = &Environment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(environment.Table, sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(environment.FieldName, field.TypeEnum, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NamespacePattern(); ok {
		_spec.SetField(environment.FieldNamespacePattern, field.TypeString, value)
		_node.NamespacePattern = value
	}
	if value, ok := _c.mutation.ApprovalRequired(); ok {
		_spec.SetField(environment.FieldApprovalRequired, field.TypeBool, value)
		_node.ApprovalRequired = value
	}
	if value, ok := _c.mutation.ApproverRole(); ok {
		_spec.SetField(environment.FieldApproverRole, field.TypeString, value)
		_node.ApproverRole = value
	}
	if value, ok := _c.mutation.ConfigOverrides(); ok {
		_spec.SetField(environment.FieldConfigOverrides, field.TypeJSON, value)
		_node.ConfigOverrides = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(environment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(environment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ClusterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ClusterTable,
			Columns: []string{environment.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClusterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.OrganizationTable,
			Columns: []string{environment.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrgID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EnvironmentCreateBulk is the builder for creating many Environment entities in bulk.
type EnvironmentCreateBulk struct {
	config
	err      error
	builders []*EnvironmentCreate
}

// Save creates the Environment entities in the database.
func (_c *EnvironmentCreateBulk) Save(ctx context.Context) ([]*Environment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Environment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnvironmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnvironmentCreateBulk) SaveX(ctx context.Context) []*Environment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvironmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvironmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
