// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/cluster"
	"github.com/whg517/fleet/internal/store/ent/environment"
	"github.com/whg517/fleet/internal/store/ent/organization"
	"github.com/whg517/fleet/internal/store/ent/predicate"
)

// EnvironmentUpdate is the builder for updating Environment entities.
type EnvironmentUpdate struct {
	config
	hooks    []Hook
	mutation *EnvironmentMutation
}

// Where appends a list predicates to the EnvironmentUpdate builder.
func (_u *EnvironmentUpdate) Where(ps ...predicate.Environment) *EnvironmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *EnvironmentUpdate) SetOrgID(v string) *EnvironmentUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableOrgID(v *string) *EnvironmentUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *EnvironmentUpdate) ClearOrgID() *EnvironmentUpdate {
	_u.mutation.ClearOrgID()
	return _u
}

// SetName sets the "name" field.
func (_u *EnvironmentUpdate) SetName(v environment.Name) *EnvironmentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableName(v *environment.Name) *EnvironmentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetClusterID sets the "cluster_id" field.
func (_u *EnvironmentUpdate) SetClusterID(v string) *EnvironmentUpdate {
	_u.mutation.SetClusterID(v)
	return _u
}

// SetNillableClusterID sets the "cluster_id" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableClusterID(v *string) *EnvironmentUpdate {
	if v != nil {
		_u.SetClusterID(*v)
	}
	return _u
}

// ClearClusterID clears the value of the "cluster_id" field.
func (_u *EnvironmentUpdate) ClearClusterID() *EnvironmentUpdate {
	_u.mutation.ClearClusterID()
	return _u
}

// SetNamespacePattern sets the "namespace_pattern" field.
func (_u *EnvironmentUpdate) SetNamespacePattern(v string) *EnvironmentUpdate {
	_u.mutation.SetNamespacePattern(v)
	return _u
}

// SetNillableNamespacePattern sets the "namespace_pattern" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableNamespacePattern(v *string) *EnvironmentUpdate {
	if v != nil {
		_u.SetNamespacePattern(*v)
	}
	return _u
}

// ClearNamespacePattern clears the value of the "namespace_pattern" field.
func (_u *EnvironmentUpdate) ClearNamespacePattern() *EnvironmentUpdate {
	_u.mutation.ClearNamespacePattern()
	return _u
}

// SetApprovalRequired sets the "approval_required" field.
func (_u *EnvironmentUpdate) SetApprovalRequired(v bool) *EnvironmentUpdate {
	_u.mutation.SetApprovalRequired(v)
	return _u
}

// SetNillableApprovalRequired sets the "approval_required" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableApprovalRequired(v *bool) *EnvironmentUpdate {
	if v != nil {
		_u.SetApprovalRequired(*v)
	}
	return _u
}

// SetApproverRole sets the "approver_role" field.
func (_u *EnvironmentUpdate) SetApproverRole(v string) *EnvironmentUpdate {
	_u.mutation.SetApproverRole(v)
	return _u
}

// SetNillableApproverRole sets the "approver_role" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableApproverRole(v *string) *EnvironmentUpdate {
	if v != nil {
		_u.SetApproverRole(*v)
	}
	return _u
}

// ClearApproverRole clears the value of the "approver_role" field.
func (_u *EnvironmentUpdate) ClearApproverRole() *EnvironmentUpdate {
	_u.mutation.ClearApproverRole()
	return _u
}

// SetConfigOverrides sets the "config_overrides" field.
func (_u *EnvironmentUpdate) SetConfigOverrides(v map[string]interface{}) *EnvironmentUpdate {
	_u.mutation.SetConfigOverrides(v)
	return _u
}

// ClearConfigOverrides clears the value of the "config_overrides" field.
func (_u *EnvironmentUpdate) ClearConfigOverrides() *EnvironmentUpdate {
	_u.mutation.ClearConfigOverrides()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvironmentUpdate) SetUpdatedAt(v time.Time) *EnvironmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCluster sets the "cluster" edge to the Cluster entity.
func (_u *EnvironmentUpdate) SetCluster(v *Cluster) *EnvironmentUpdate {
	return _u.SetClusterID(v.ID)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *EnvironmentUpdate) SetOrganizationID(id string) *EnvironmentUpdate {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableOrganizationID(id *string) *EnvironmentUpdate {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *EnvironmentUpdate) SetOrganization(v *Organization) *EnvironmentUpdate {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the EnvironmentMutation object of the builder.
func (_u *EnvironmentUpdate) Mutation() *EnvironmentMutation {
	return _u.mutation
}

// ClearCluster clears the "cluster" edge to the Cluster entity.
func (_u *EnvironmentUpdate) ClearCluster() *EnvironmentUpdate {
	_u.mutation.ClearCluster()
	return _u
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *EnvironmentUpdate) ClearOrganization() *EnvironmentUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnvironmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvironmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnvironmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvironmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvironmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := environment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvironmentUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := environment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Environment.name": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvironmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(environment.Table, environment.Columns, sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(environment.FieldName, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NamespacePattern(); ok {
		_spec.SetField(environment.FieldNamespacePattern, field.TypeString, value)
	}
	if _u.mutation.NamespacePatternCleared() {
		_spec.ClearField(environment.FieldNamespacePattern, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovalRequired(); ok {
		_spec.SetField(environment.FieldApprovalRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ApproverRole(); ok {
		_spec.SetField(environment.FieldApproverRole, field.TypeString, value)
	}
	if _u.mutation.ApproverRoleCleared() {
		_spec.ClearField(environment.FieldApproverRole, field.TypeString)
	}
	if value, ok := _u.mutation.ConfigOverrides(); ok {
		_spec.SetField(environment.FieldConfigOverrides, field.TypeJSON, value)
	}
	if _u.mutation.ConfigOverridesCleared() {
		_spec.ClearField(environment.FieldConfigOverrides, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(environment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ClusterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ClusterTable,
			Columns: []string{environment.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClusterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ClusterTable,
			Columns: []string{environment.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.OrganizationTable,
			Columns: []string{environment.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.OrganizationTable,
			Columns: []string{environment.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{environment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnvironmentUpdateOne is the builder for updating a single Environment entity.
type EnvironmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnvironmentMutation
}

// SetOrgID sets the "org_id" field.
func (_u *EnvironmentUpdateOne) SetOrgID(v string) *EnvironmentUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableOrgID(v *string) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *EnvironmentUpdateOne) ClearOrgID() *EnvironmentUpdateOne {
	_u.mutation.ClearOrgID()
	return _u
}

// SetName sets the "name" field.
func (_u *EnvironmentUpdateOne) SetName(v environment.Name) *EnvironmentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableName(v *environment.Name) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetClusterID sets the "cluster_id" field.
func (_u *EnvironmentUpdateOne) SetClusterID(v string) *EnvironmentUpdateOne {
	_u.mutation.SetClusterID(v)
	return _u
}

// SetNillableClusterID sets the "cluster_id" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableClusterID(v *string) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetClusterID(*v)
	}
	return _u
}

// ClearClusterID clears the value of the "cluster_id" field.
func (_u *EnvironmentUpdateOne) ClearClusterID() *EnvironmentUpdateOne {
	_u.mutation.ClearClusterID()
	return _u
}

// SetNamespacePattern sets the "namespace_pattern" field.
func (_u *EnvironmentUpdateOne) SetNamespacePattern(v string) *EnvironmentUpdateOne {
	_u.mutation.SetNamespacePattern(v)
	return _u
}

// SetNillableNamespacePattern sets the "namespace_pattern" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableNamespacePattern(v *string) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetNamespacePattern(*v)
	}
	return _u
}

// ClearNamespacePattern clears the value of the "namespace_pattern" field.
func (_u *EnvironmentUpdateOne) ClearNamespacePattern() *EnvironmentUpdateOne {
	_u.mutation.ClearNamespacePattern()
	return _u
}

// SetApprovalRequired sets the "approval_required" field.
func (_u *EnvironmentUpdateOne) SetApprovalRequired(v bool) *EnvironmentUpdateOne {
	_u.mutation.SetApprovalRequired(v)
	return _u
}

// SetNillableApprovalRequired sets the "approval_required" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableApprovalRequired(v *bool) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetApprovalRequired(*v)
	}
	return _u
}

// SetApproverRole sets the "approver_role" field.
func (_u *EnvironmentUpdateOne) SetApproverRole(v string) *EnvironmentUpdateOne {
	_u.mutation.SetApproverRole(v)
	return _u
}

// SetNillableApproverRole sets the "approver_role" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableApproverRole(v *string) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetApproverRole(*v)
	}
	return _u
}

// ClearApproverRole clears the value of the "approver_role" field.
func (_u *EnvironmentUpdateOne) ClearApproverRole() *EnvironmentUpdateOne {
	_u.mutation.ClearApproverRole()
	return _u
}

// SetConfigOverrides sets the "config_overrides" field.
func (_u *EnvironmentUpdateOne) SetConfigOverrides(v map[string]interface{}) *EnvironmentUpdateOne {
	_u.mutation.SetConfigOverrides(v)
	return _u
}

// ClearConfigOverrides clears the value of the "config_overrides" field.
func (_u *EnvironmentUpdateOne) ClearConfigOverrides() *EnvironmentUpdateOne {
	_u.mutation.ClearConfigOverrides()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvironmentUpdateOne) SetUpdatedAt(v time.Time) *EnvironmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCluster sets the "cluster" edge to the Cluster entity.
func (_u *EnvironmentUpdateOne) SetCluster(v *Cluster) *EnvironmentUpdateOne {
	return _u.SetClusterID(v.ID)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *EnvironmentUpdateOne) SetOrganizationID(id string) *EnvironmentUpdateOne {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableOrganizationID(id *string) *EnvironmentUpdateOne {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *EnvironmentUpdateOne) SetOrganization(v *Organization) *EnvironmentUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the EnvironmentMutation object of the builder.
func (_u *EnvironmentUpdateOne) Mutation() *EnvironmentMutation {
	return _u.mutation
}

// ClearCluster clears the "cluster" edge to the Cluster entity.
func (_u *EnvironmentUpdateOne) ClearCluster() *EnvironmentUpdateOne {
	_u.mutation.ClearCluster()
	return _u
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *EnvironmentUpdateOne) ClearOrganization() *EnvironmentUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// Where appends a list predicates to the EnvironmentUpdate builder.
func (_u *EnvironmentUpdateOne) Where(ps ...predicate.Environment) *EnvironmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnvironmentUpdateOne) Select(field string, fields ...string) *EnvironmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Environment entity.
func (_u *EnvironmentUpdateOne) Save(ctx context.Context) (*Environment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvironmentUpdateOne) SaveX(ctx context.Context) *Environment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnvironmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvironmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvironmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := environment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvironmentUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := environment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Environment.name": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvironmentUpdateOne) sqlSave(ctx context.Context) (_node *Environment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(environment.Table, environment.Columns, sqlgraph.NewFieldSpec(environment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Environment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, environment.FieldID)
		for _, f := range fields {
			if !environment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != environment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(environment.FieldName, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NamespacePattern(); ok {
		_spec.SetField(environment.FieldNamespacePattern, field.TypeString, value)
	}
	if _u.mutation.NamespacePatternCleared() {
		_spec.ClearField(environment.FieldNamespacePattern, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovalRequired(); ok {
		_spec.SetField(environment.FieldApprovalRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ApproverRole(); ok {
		_spec.SetField(environment.FieldApproverRole, field.TypeString, value)
	}
	if _u.mutation.ApproverRoleCleared() {
		_spec.ClearField(environment.FieldApproverRole, field.TypeString)
	}
	if value, ok := _u.mutation.ConfigOverrides(); ok {
		_spec.SetField(environment.FieldConfigOverrides, field.TypeJSON, value)
	}
	if _u.mutation.ConfigOverridesCleared() {
		_spec.ClearField(environment.FieldConfigOverrides, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(environment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ClusterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ClusterTable,
			Columns: []string{environment.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClusterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ClusterTable,
			Columns: []string{environment.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.OrganizationTable,
			Columns: []string{environment.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.OrganizationTable,
			Columns: []string{environment.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Environment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{environment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
