// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/organization"
	"github.com/whg517/fleet/internal/store/ent/service"
)

// ServiceCreate is the builder for creating a Service entity.
type ServiceCreate struct {
	config
	mutation *ServiceMutation
	hooks    []Hook
}

// SetOrgID sets the "org_id" field.
func (_c *ServiceCreate) SetOrgID(v string) *ServiceCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_c *ServiceCreate) SetNillableOrgID(v *string) *ServiceCreate {
	if v != nil {
		_c.SetOrgID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ServiceCreate) SetName(v string) *ServiceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTeam sets the "team" field.
func (_c *ServiceCreate) SetTeam(v string) *ServiceCreate {
	_c.mutation.SetTeam(v)
	return _c
}

// SetNillableTeam sets the "team" field if the given value is not nil.
func (_c *ServiceCreate) SetNillableTeam(v *string) *ServiceCreate {
	if v != nil {
		_c.SetTeam(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ServiceCreate) SetDescription(v string) *ServiceCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ServiceCreate) SetNillableDescription(v *string) *ServiceCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *ServiceCreate) SetLabels(v map[string]string) *ServiceCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ServiceCreate) SetStatus(v service.Status) *ServiceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ServiceCreate) SetNillableStatus(v *service.Status) *ServiceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetHarborProject sets the "harbor_project" field.
func (_c *ServiceCreate) SetHarborProject(v string) *ServiceCreate {
	_c.mutation.SetHarborProject(v)
	return _c
}

// SetNillableHarborProject sets the "harbor_project" field if the given value is not nil.
func (_c *ServiceCreate) SetNillableHarborProject(v *string) *ServiceCreate {
	if v != nil {
		_c.SetHarborProject(*v)
	}
	return _c
}

// SetGitRepo sets the "git_repo" field.
func (_c *ServiceCreate) SetGitRepo(v string) *ServiceCreate {
	_c.mutation.SetGitRepo(v)
	return _c
}

// SetNillableGitRepo sets the "git_repo" field if the given value is not nil.
func (_c *ServiceCreate) SetNillableGitRepo(v *string) *ServiceCreate {
	if v != nil {
		_c.SetGitRepo(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ServiceCreate) SetCreatedAt(v time.Time) *ServiceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ServiceCreate) SetNillableCreatedAt(v *time.Time) *ServiceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ServiceCreate) SetUpdatedAt(v time.Time) *ServiceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ServiceCreate) SetNillableUpdatedAt(v *time.Time) *ServiceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ServiceCreate) SetID(v string) *ServiceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_c *ServiceCreate) SetOrganizationID(id string) *ServiceCreate {
	_c.mutation.SetOrganizationID(id)
	return _c
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_c *ServiceCreate) SetNillableOrganizationID(id *string) *ServiceCreate {
	if id != nil {
		_c = _c.SetOrganizationID(*id)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *ServiceCreate) SetOrganization(v *Organization) *ServiceCreate {
	return _c.SetOrganizationID(v.ID)
}

// Mutation returns the ServiceMutation object of the builder.
func (_c *ServiceCreate) Mutation() *ServiceMutation {
	return _c.mutation
}

// Save creates the Service in the database.
func (_c *ServiceCreate) Save(ctx context.Context) (*Service, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ServiceCreate) SaveX(ctx context.Context) *Service {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ServiceCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := service.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := service.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := service.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ServiceCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Service.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := service.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Service.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Service.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := service.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Service.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Service.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Service.updated_at"`)}
	}
	return nil
}

func (_c *ServiceCreate) sqlSave(ctx context.Context) (*Service, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Service.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ServiceCreate) createSpec() (*Service, *sqlgraph.CreateSpec) {
	var (
		_node = &Service{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(service.Table, sqlgraph.NewFieldSpec(service.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(service.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Team(); ok {
		_spec.SetField(service.FieldTeam, field.TypeString, value)
		_node.Team = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(service.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(service.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(service.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.HarborProject(); ok {
		_spec.SetField(service.FieldHarborProject, field.TypeString, value)
		_node.HarborProject = value
	}
	if value, ok := _c.mutation.GitRepo(); ok {
		_spec.SetField(service.FieldGitRepo, field.TypeString, value)
		_node.GitRepo = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(service.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(service.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.OrganizationTable,
			Columns: []string{service.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrgID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ServiceCreateBulk is the builder for creating many Service entities in bulk.
type ServiceCreateBulk struct {
	config
	err      error
	builders []*ServiceCreate
}

// Save creates the Service entities in the database.
func (_c *ServiceCreateBulk) Save(ctx context.Context) ([]*Service, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Service, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ServiceCreateBulk) SaveX(ctx context.Context) []*Service {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
