// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/organization"
	"github.com/whg517/fleet/internal/store/ent/predicate"
	"github.com/whg517/fleet/internal/store/ent/template"
	"github.com/whg517/fleet/internal/store/ent/templateversion"
)

// TemplateUpdate is the builder for updating Template entities.
type TemplateUpdate struct {
	config
	hooks    []Hook
	mutation *TemplateMutation
}

// Where appends a list predicates to the TemplateUpdate builder.
func (_u *TemplateUpdate) Where(ps ...predicate.Template) *TemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *TemplateUpdate) SetOrgID(v string) *TemplateUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableOrgID(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *TemplateUpdate) ClearOrgID() *TemplateUpdate {
	_u.mutation.ClearOrgID()
	return _u
}

// SetName sets the "name" field.
func (_u *TemplateUpdate) SetName(v string) *TemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableName(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TemplateUpdate) SetType(v template.Type) *TemplateUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableType(v *template.Type) *TemplateUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *TemplateUpdate) SetSource(v template.Source) *TemplateUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableSource(v *template.Source) *TemplateUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRegistryID sets the "registry_id" field.
func (_u *TemplateUpdate) SetRegistryID(v string) *TemplateUpdate {
	_u.mutation.SetRegistryID(v)
	return _u
}

// SetNillableRegistryID sets the "registry_id" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableRegistryID(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetRegistryID(*v)
	}
	return _u
}

// ClearRegistryID clears the value of the "registry_id" field.
func (_u *TemplateUpdate) ClearRegistryID() *TemplateUpdate {
	_u.mutation.ClearRegistryID()
	return _u
}

// SetRepo sets the "repo" field.
func (_u *TemplateUpdate) SetRepo(v string) *TemplateUpdate {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableRepo(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// ClearRepo clears the value of the "repo" field.
func (_u *TemplateUpdate) ClearRepo() *TemplateUpdate {
	_u.mutation.ClearRepo()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TemplateUpdate) SetDescription(v string) *TemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableDescription(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TemplateUpdate) ClearDescription() *TemplateUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TemplateUpdate) SetStatus(v template.Status) *TemplateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableStatus(v *template.Status) *TemplateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TemplateUpdate) SetUpdatedAt(v time.Time) *TemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddVersionIDs adds the "versions" edge to the TemplateVersion entity by IDs.
func (_u *TemplateUpdate) AddVersionIDs(ids ...string) *TemplateUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the TemplateVersion entity.
func (_u *TemplateUpdate) AddVersions(v ...*TemplateVersion) *TemplateUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *TemplateUpdate) SetOrganizationID(id string) *TemplateUpdate {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *TemplateUpdate) SetNillableOrganizationID(id *string) *TemplateUpdate {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *TemplateUpdate) SetOrganization(v *Organization) *TemplateUpdate {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the TemplateMutation object of the builder.
func (_u *TemplateUpdate) Mutation() *TemplateMutation {
	return _u.mutation
}

// ClearVersions clears all "versions" edges to the TemplateVersion entity.
func (_u *TemplateUpdate) ClearVersions() *TemplateUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to TemplateVersion entities by IDs.
func (_u *TemplateUpdate) RemoveVersionIDs(ids ...string) *TemplateUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to TemplateVersion entities.
func (_u *TemplateUpdate) RemoveVersions(v ...*TemplateVersion) *TemplateUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *TemplateUpdate) ClearOrganization() *TemplateUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TemplateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TemplateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := template.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := template.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Template.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := template.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Template.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := template.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Template.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(template.Table, template.Columns, sqlgraph.NewFieldSpec(template.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(template.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(template.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RegistryID(); ok {
		_spec.SetField(template.FieldRegistryID, field.TypeString, value)
	}
	if _u.mutation.RegistryIDCleared() {
		_spec.ClearField(template.FieldRegistryID, field.TypeString)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(template.FieldRepo, field.TypeString, value)
	}
	if _u.mutation.RepoCleared() {
		_spec.ClearField(template.FieldRepo, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(template.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(template.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(template.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(template.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.VersionsTable,
			Columns: []string{template.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templateversion.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.VersionsTable,
			Columns: []string{template.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templateversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.VersionsTable,
			Columns: []string{template.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templateversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.OrganizationTable,
			Columns: []string{template.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.OrganizationTable,
			Columns: []string{template.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{template.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TemplateUpdateOne is the builder for updating a single Template entity.
type TemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TemplateMutation
}

// SetOrgID sets the "org_id" field.
func (_u *TemplateUpdateOne) SetOrgID(v string) *TemplateUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableOrgID(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *TemplateUpdateOne) ClearOrgID() *TemplateUpdateOne {
	_u.mutation.ClearOrgID()
	return _u
}

// SetName sets the "name" field.
func (_u *TemplateUpdateOne) SetName(v string) *TemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableName(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TemplateUpdateOne) SetType(v template.Type) *TemplateUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableType(v *template.Type) *TemplateUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *TemplateUpdateOne) SetSource(v template.Source) *TemplateUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableSource(v *template.Source) *TemplateUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRegistryID sets the "registry_id" field.
func (_u *TemplateUpdateOne) SetRegistryID(v string) *TemplateUpdateOne {
	_u.mutation.SetRegistryID(v)
	return _u
}

// SetNillableRegistryID sets the "registry_id" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableRegistryID(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetRegistryID(*v)
	}
	return _u
}

// ClearRegistryID clears the value of the "registry_id" field.
func (_u *TemplateUpdateOne) ClearRegistryID() *TemplateUpdateOne {
	_u.mutation.ClearRegistryID()
	return _u
}

// SetRepo sets the "repo" field.
func (_u *TemplateUpdateOne) SetRepo(v string) *TemplateUpdateOne {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableRepo(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// ClearRepo clears the value of the "repo" field.
func (_u *TemplateUpdateOne) ClearRepo() *TemplateUpdateOne {
	_u.mutation.ClearRepo()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TemplateUpdateOne) SetDescription(v string) *TemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableDescription(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TemplateUpdateOne) ClearDescription() *TemplateUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TemplateUpdateOne) SetStatus(v template.Status) *TemplateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableStatus(v *template.Status) *TemplateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TemplateUpdateOne) SetUpdatedAt(v time.Time) *TemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddVersionIDs adds the "versions" edge to the TemplateVersion entity by IDs.
func (_u *TemplateUpdateOne) AddVersionIDs(ids ...string) *TemplateUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the TemplateVersion entity.
func (_u *TemplateUpdateOne) AddVersions(v ...*TemplateVersion) *TemplateUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *TemplateUpdateOne) SetOrganizationID(id string) *TemplateUpdateOne {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableOrganizationID(id *string) *TemplateUpdateOne {
	if id != nil {
		_u = _u.SetOrganizationID(*id)
	}
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *TemplateUpdateOne) SetOrganization(v *Organization) *TemplateUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the TemplateMutation object of the builder.
func (_u *TemplateUpdateOne) Mutation() *TemplateMutation {
	return _u.mutation
}

// ClearVersions clears all "versions" edges to the TemplateVersion entity.
func (_u *TemplateUpdateOne) ClearVersions() *TemplateUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to TemplateVersion entities by IDs.
func (_u *TemplateUpdateOne) RemoveVersionIDs(ids ...string) *TemplateUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to TemplateVersion entities.
func (_u *TemplateUpdateOne) RemoveVersions(v ...*TemplateVersion) *TemplateUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *TemplateUpdateOne) ClearOrganization() *TemplateUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// Where appends a list predicates to the TemplateUpdate builder.
func (_u *TemplateUpdateOne) Where(ps ...predicate.Template) *TemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TemplateUpdateOne) Select(field string, fields ...string) *TemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Template entity.
func (_u *TemplateUpdateOne) Save(ctx context.Context) (*Template, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateUpdateOne) SaveX(ctx context.Context) *Template {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TemplateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := template.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := template.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Template.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := template.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Template.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := template.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Template.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TemplateUpdateOne) sqlSave(ctx context.Context) (_node *Template, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(template.Table, template.Columns, sqlgraph.NewFieldSpec(template.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Template.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, template.FieldID)
		for _, f := range fields {
			if !template.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != template.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(template.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(template.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RegistryID(); ok {
		_spec.SetField(template.FieldRegistryID, field.TypeString, value)
	}
	if _u.mutation.RegistryIDCleared() {
		_spec.ClearField(template.FieldRegistryID, field.TypeString)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(template.FieldRepo, field.TypeString, value)
	}
	if _u.mutation.RepoCleared() {
		_spec.ClearField(template.FieldRepo, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(template.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(template.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(template.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(template.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.VersionsTable,
			Columns: []string{template.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templateversion.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.VersionsTable,
			Columns: []string{template.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templateversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.VersionsTable,
			Columns: []string{template.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templateversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.OrganizationTable,
			Columns: []string{template.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.OrganizationTable,
			Columns: []string{template.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Template{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{template.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
