// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/fleet/internal/store/ent/predicate"
	"github.com/whg517/fleet/internal/store/ent/template"
	"github.com/whg517/fleet/internal/store/ent/templateversion"
)

// TemplateVersionUpdate is the builder for updating TemplateVersion entities.
type TemplateVersionUpdate struct {
	config
	hooks    []Hook
	mutation *TemplateVersionMutation
}

// Where appends a list predicates to the TemplateVersionUpdate builder.
func (_u *TemplateVersionUpdate) Where(ps ...predicate.TemplateVersion) *TemplateVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *TemplateVersionUpdate) SetTemplateID(v string) *TemplateVersionUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *TemplateVersionUpdate) SetNillableTemplateID(v *string) *TemplateVersionUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *TemplateVersionUpdate) SetVersion(v string) *TemplateVersionUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TemplateVersionUpdate) SetNillableVersion(v *string) *TemplateVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetDigest sets the "digest" field.
func (_u *TemplateVersionUpdate) SetDigest(v string) *TemplateVersionUpdate {
	_u.mutation.SetDigest(v)
	return _u
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (_u *TemplateVersionUpdate) SetNillableDigest(v *string) *TemplateVersionUpdate {
	if v != nil {
		_u.SetDigest(*v)
	}
	return _u
}

// ClearDigest clears the value of the "digest" field.
func (_u *TemplateVersionUpdate) ClearDigest() *TemplateVersionUpdate {
	_u.mutation.ClearDigest()
	return _u
}

// SetValuesSchema sets the "values_schema" field.
func (_u *TemplateVersionUpdate) SetValuesSchema(v map[string]interface{}) *TemplateVersionUpdate {
	_u.mutation.SetValuesSchema(v)
	return _u
}

// ClearValuesSchema clears the value of the "values_schema" field.
func (_u *TemplateVersionUpdate) ClearValuesSchema() *TemplateVersionUpdate {
	_u.mutation.ClearValuesSchema()
	return _u
}

// SetChangelog sets the "changelog" field.
func (_u *TemplateVersionUpdate) SetChangelog(v string) *TemplateVersionUpdate {
	_u.mutation.SetChangelog(v)
	return _u
}

// SetNillableChangelog sets the "changelog" field if the given value is not nil.
func (_u *TemplateVersionUpdate) SetNillableChangelog(v *string) *TemplateVersionUpdate {
	if v != nil {
		_u.SetChangelog(*v)
	}
	return _u
}

// ClearChangelog clears the value of the "changelog" field.
func (_u *TemplateVersionUpdate) ClearChangelog() *TemplateVersionUpdate {
	_u.mutation.ClearChangelog()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TemplateVersionUpdate) SetStatus(v templateversion.Status) *TemplateVersionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TemplateVersionUpdate) SetNillableStatus(v *templateversion.Status) *TemplateVersionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTemplate sets the "template" edge to the Template entity.
func (_u *TemplateVersionUpdate) SetTemplate(v *Template) *TemplateVersionUpdate {
	return _u.SetTemplateID(v.ID)
}

// Mutation returns the TemplateVersionMutation object of the builder.
func (_u *TemplateVersionUpdate) Mutation() *TemplateVersionMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the Template entity.
func (_u *TemplateVersionUpdate) ClearTemplate() *TemplateVersionUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TemplateVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TemplateVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateVersionUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := templateversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "TemplateVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := templateversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TemplateVersion.status": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TemplateVersion.template"`)
	}
	return nil
}

func (_u *TemplateVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(templateversion.Table, templateversion.Columns, sqlgraph.NewFieldSpec(templateversion.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(templateversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Digest(); ok {
		_spec.SetField(templateversion.FieldDigest, field.TypeString, value)
	}
	if _u.mutation.DigestCleared() {
		_spec.ClearField(templateversion.FieldDigest, field.TypeString)
	}
	if value, ok := _u.mutation.ValuesSchema(); ok {
		_spec.SetField(templateversion.FieldValuesSchema, field.TypeJSON, value)
	}
	if _u.mutation.ValuesSchemaCleared() {
		_spec.ClearField(templateversion.FieldValuesSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.Changelog(); ok {
		_spec.SetField(templateversion.FieldChangelog, field.TypeString, value)
	}
	if _u.mutation.ChangelogCleared() {
		_spec.ClearField(templateversion.FieldChangelog, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(templateversion.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templateversion.TemplateTable,
			Columns: []string{templateversion.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templateversion.TemplateTable,
			Columns: []string{templateversion.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templateversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TemplateVersionUpdateOne is the builder for updating a single TemplateVersion entity.
type TemplateVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TemplateVersionMutation
}

// SetTemplateID sets the "template_id" field.
func (_u *TemplateVersionUpdateOne) SetTemplateID(v string) *TemplateVersionUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *TemplateVersionUpdateOne) SetNillableTemplateID(v *string) *TemplateVersionUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *TemplateVersionUpdateOne) SetVersion(v string) *TemplateVersionUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TemplateVersionUpdateOne) SetNillableVersion(v *string) *TemplateVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetDigest sets the "digest" field.
func (_u *TemplateVersionUpdateOne) SetDigest(v string) *TemplateVersionUpdateOne {
	_u.mutation.SetDigest(v)
	return _u
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (_u *TemplateVersionUpdateOne) SetNillableDigest(v *string) *TemplateVersionUpdateOne {
	if v != nil {
		_u.SetDigest(*v)
	}
	return _u
}

// ClearDigest clears the value of the "digest" field.
func (_u *TemplateVersionUpdateOne) ClearDigest() *TemplateVersionUpdateOne {
	_u.mutation.ClearDigest()
	return _u
}

// SetValuesSchema sets the "values_schema" field.
func (_u *TemplateVersionUpdateOne) SetValuesSchema(v map[string]interface{}) *TemplateVersionUpdateOne {
	_u.mutation.SetValuesSchema(v)
	return _u
}

// ClearValuesSchema clears the value of the "values_schema" field.
func (_u *TemplateVersionUpdateOne) ClearValuesSchema() *TemplateVersionUpdateOne {
	_u.mutation.ClearValuesSchema()
	return _u
}

// SetChangelog sets the "changelog" field.
func (_u *TemplateVersionUpdateOne) SetChangelog(v string) *TemplateVersionUpdateOne {
	_u.mutation.SetChangelog(v)
	return _u
}

// SetNillableChangelog sets the "changelog" field if the given value is not nil.
func (_u *TemplateVersionUpdateOne) SetNillableChangelog(v *string) *TemplateVersionUpdateOne {
	if v != nil {
		_u.SetChangelog(*v)
	}
	return _u
}

// ClearChangelog clears the value of the "changelog" field.
func (_u *TemplateVersionUpdateOne) ClearChangelog() *TemplateVersionUpdateOne {
	_u.mutation.ClearChangelog()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TemplateVersionUpdateOne) SetStatus(v templateversion.Status) *TemplateVersionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TemplateVersionUpdateOne) SetNillableStatus(v *templateversion.Status) *TemplateVersionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTemplate sets the "template" edge to the Template entity.
func (_u *TemplateVersionUpdateOne) SetTemplate(v *Template) *TemplateVersionUpdateOne {
	return _u.SetTemplateID(v.ID)
}

// Mutation returns the TemplateVersionMutation object of the builder.
func (_u *TemplateVersionUpdateOne) Mutation() *TemplateVersionMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the Template entity.
func (_u *TemplateVersionUpdateOne) ClearTemplate() *TemplateVersionUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// Where appends a list predicates to the TemplateVersionUpdate builder.
func (_u *TemplateVersionUpdateOne) Where(ps ...predicate.TemplateVersion) *TemplateVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TemplateVersionUpdateOne) Select(field string, fields ...string) *TemplateVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TemplateVersion entity.
func (_u *TemplateVersionUpdateOne) Save(ctx context.Context) (*TemplateVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateVersionUpdateOne) SaveX(ctx context.Context) *TemplateVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TemplateVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := templateversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "TemplateVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := templateversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TemplateVersion.status": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TemplateVersion.template"`)
	}
	return nil
}

func (_u *TemplateVersionUpdateOne) sqlSave(ctx context.Context) (_node *TemplateVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(templateversion.Table, templateversion.Columns, sqlgraph.NewFieldSpec(templateversion.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TemplateVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, templateversion.FieldID)
		for _, f := range fields {
			if !templateversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != templateversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(templateversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Digest(); ok {
		_spec.SetField(templateversion.FieldDigest, field.TypeString, value)
	}
	if _u.mutation.DigestCleared() {
		_spec.ClearField(templateversion.FieldDigest, field.TypeString)
	}
	if value, ok := _u.mutation.ValuesSchema(); ok {
		_spec.SetField(templateversion.FieldValuesSchema, field.TypeJSON, value)
	}
	if _u.mutation.ValuesSchemaCleared() {
		_spec.ClearField(templateversion.FieldValuesSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.Changelog(); ok {
		_spec.SetField(templateversion.FieldChangelog, field.TypeString, value)
	}
	if _u.mutation.ChangelogCleared() {
		_spec.ClearField(templateversion.FieldChangelog, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(templateversion.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templateversion.TemplateTable,
			Columns: []string{templateversion.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templateversion.TemplateTable,
			Columns: []string{templateversion.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TemplateVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templateversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
