// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Approval is the predicate function for approval builders.
type Approval func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Cluster is the predicate function for cluster builders.
type Cluster func(*sql.Selector)

// ConfigSnapshot is the predicate function for configsnapshot builders.
type ConfigSnapshot func(*sql.Selector)

// Deployment is the predicate function for deployment builders.
type Deployment func(*sql.Selector)

// Environment is the predicate function for environment builders.
type Environment func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// Registry is the predicate function for registry builders.
type Registry func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// SystemSetting is the predicate function for systemsetting builders.
type SystemSetting func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)

// TemplateVersion is the predicate function for templateversion builders.
type TemplateVersion func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
