apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleet.fullname" . }}-secret
  labels:
    {{- include "fleet.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ required "secrets.databasePassword is required" .Values.secrets.databasePassword | quote }}
  REDIS_PASSWORD: {{ required "secrets.redisPassword is required" .Values.secrets.redisPassword | quote }}
  OIDC_CLIENT_SECRET: {{ required "secrets.oidcClientSecret is required" .Values.secrets.oidcClientSecret | quote }}
  JWT_SECRET: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
